### ISSUE TITLE
Node.js Engineer 

### ISSUE THREAD

**Issue by AvengerMoJo** [nodejs-tw/jobs#1]
工作職稱：系統設計師 - 協助公司開發網站或應用系統 & 公司資訊系統之日常維護
職務類別：軟體設計工程師、後台系統維護
工作待遇：面議
工作性質：全職
上班地點：台北市內湖區
管理責任：不需負擔管理責任
出差外派：無需出差外派
擅長工具：LINUX、JavaScript、jQuery
工作技能：伺服器網站管理維護、軟體工程系統開發
以上，如有任何問題，請隨時與我alex@avengergear.com聯絡，謝謝！

**Comment by dca** [comment]
請問這個已經找到人了嗎?

**Comment by AvengerMoJo** [comment]
Hey :) just saw your email. No still looking. Please send me resume if you
are I interested.

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
