### ISSUE TITLE
太和光科技 - [求才] Javascript full-stack 全端工程師

### ISSUE THREAD

**Issue by chihyi1980** [nodejs-tw/jobs#10]
**太和光科技徵求 Javascipt full-stack 全端工程師**
大家好，我們是太和光科技，長期致力於物聯網相關產業發展，近期跨入工業4.0中智能導航領域，為醫院、博物館、工廠、保全系統提供人員、設備定位監控服務，急需軟體高手一同加入打拼
相關報導請參考：
數位時代報導
http://www.bnext.com.tw/article/view/id/28985
微光計畫 - 盲人導航
http://www.ettoday.net/news/20150511/505146.htm
- 基本技能需求

HTML、CSS、Javascript、Linux基礎指令操作
JS套件
Bootstrap、node.js express、Angular
資料庫
mongo db
- 加分項
1. AWS雲端伺服器佈署經驗
2. mongo db 叢集佈署經驗
3. 高併發量要求處理經驗
4. 遠端團隊協同工作經驗
5. 整合第三方SDK經驗(例如google map)
- 薪資範圍

50k~60k NTD
工作地點
新北市三重區湯城園區
- 注意事項
1. 上班時間不強制打卡，但須在指定時間內完成進度
2. 有國內短期出差與駐點工作的需求
3. 預計半年內工作都是匯報給遠端的主管，以skype與qq溝通，定期review進度, 所以不依靠他人獨立作戰的能力十分重要
- 聯絡方式

請將履歷投遞至 chihyi1980@gmail.com
如有作品敬請附上github link

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
