### ISSUE TITLE
[台灣新創徵才] nodejs Developer 1797.tw 一起救急 一起借錢 全職工作 薪水自備 可簽約定股權

### ISSUE THREAD

**Issue by Wolke** [nodejs-tw/jobs#11]
[工作職缺]
Node.js Developer

[公司名稱與招募背景]
1797.tw是創辦人2016年過年前發現身上都沒錢了，想要找個管道借錢，Google 一下 發現全部都是銀行,當舖,信貸公司,車行,通信行,私人借款等廣告，而且所有廣告找不到任何對應的評價，另外也Google到，每年都有地下錢莊的陷阱被抓到的新聞，也就是全部看起來一模一樣的廣告裡，無法分辯誰是正派經營的業者，而誰又是陷阱。於是就興起了創建1797.tw，成立世界上第一個群眾借貸評價平台。

剛上線十多天，目前已是新北創力坊的育成團隊。
2016年3月17日將代表台灣參加asiabeat，其他與會團隊不乏已募資千萬，人數二十人以上團隊。

如果你也想把自已丟進困境裡，一同了解我們主要使用者，所正在面對的人生挑戰、與我們團隊一起解決使用者們人生最後的財務問題(因為他們下一步可能是跳樓，而這不是跟你開玩笑的)，我們所面對的問題非常非常非常具有挑戰性，歡迎你與我們連絡！

[需求條件]
熟悉node.js,aws.

[工作方式]
目前和創辦人一起 pair coding.

[酬勞]
自備。
可簽約定股權。如果有執行的那一天的話。科科

[地點]
新北創力坊(目前)

[時間]
一起coding。

[聯絡方式]
請直接email林先生 (wolkesau@gmail.com)
信中歡迎簡單說明你目前nodejs學多久，有什麼參考作品，自備多少薪水可以撐多久，為什麼想加入?

**Comment by middle2** [comment]
哈哈哈哈哈哈哈

**Comment by shawn3298317** [comment]
XD wtf

**Comment by rickypai** [comment]
請問您酬勞自備多少？

**Comment by Wolke** [comment]
只要你確定自已活的下去就行了。
都沒有人回這個：
信中歡迎簡單說明你目前nodejs學多久，有什麼參考作品，自備多少薪水可以撐多久，為什麼想加入?

**Comment by rickypai** [comment]
如果要一起執行下去的話，我也得知道你自備多少啊。如果我自備能活得比你久怎麼辦？之後留下一個單打獨鬥？

**Comment by SansWord** [comment]
搜尋『P2P 借款』可以看到有些公司已經開始實驗這種生意～
要不要看看他們遇到的困境？
[p2p借貸可以爆得好大鑊@立場新聞](http://thestandnews.com/finance/p2p%E5%80%9F%E8%B2%B8%E5%8F%AF%E4%BB%A5%E7%88%86%E5%BE%97%E5%A5%BD%E5%A4%A7%E9%91%8A/)

那您的又有怎樣的背景(非技術的資源)，可以處理相關問題呢？

**Comment by zx1986** [comment]
這個在台灣是否會有借貸的法律問題？
弄得不好就都是地下錢莊了 ...

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！

**Comment by rickypai** [comment]
轉眼一年了阿... [貴公司](https://1797.tw/)感執行得不錯. 當初不早說自己至少自備了一年. 

感覺 小氣
