### ISSUE TITLE
軟體開發工程師-PHP 

### ISSUE THREAD

**Issue by junaldwang** [nodejs-tw/jobs#112]
公司介紹: 以研發遊戲為主軸的軟體開發團隊
工作地點: 台北市
薪資範圍: 40,000~60,000/月
工作職掌：
1. 負責公司相關產品業務平台的開發。
2.參與專案中業務功能串接協議和基礎函數庫的設計，解決專案中的關鍵問題和技術難題。
3. 伺服器端相關接口開發。
4. 按時完成公司交付的各項任務。
5. 有Linux 相關操作經驗者佳。

需求條件：
1. 有2~3年PHP相關的軟體開發工作經驗，對於OOP、資料結構、HTTP網路協定有一定了解，curl抓取
資料須很熟悉流程。
2. 有HTML/CSS/JavaScript相關的工作經驗，熟悉HTTP前端跨網域傳送資料，能解決跨瀏覽器問題。
3. 有版本管理經驗 (Git或SVN)。
4. 具有資料庫，MySQL或Oracle的經驗。
5. 可以完全理解MVC。
6. 良好的溝通、團隊合作、獨立作業的能力，對網頁效能持續提升有熱情。
7. 學歷要求：專科/大學/碩士, 資訊工程相關、應用數學相關
8. 擅長工具：​Linux​、​Java​、​PHP​、​MySQL​、​HTML​、​JavaScript
9. 其他條件：歡迎 JAVA 工程師轉職

假如你有興趣，請連繫我
email: junald.wang@htclink.com
Mobile: 0932301478
Junald Wang

**Comment by dca** [comment]
發了兩篇都沒有要 Node.js 的人，走錯了嗎？

**Comment by junaldwang** [comment]
是的，我會撤掉

**Comment by junaldwang** [comment]
很抱歉，請問您有無c# 和PHP的台灣論壇相關網站資訊?可否推薦一下?謝謝您!
