### ISSUE TITLE
[徵才] 雲端技術軟體工程師-Frontend x 1名

### ISSUE THREAD

**Issue by junaldwang** [nodejs-tw/jobs#115]
聯絡人: Junald Wang, email junald.wang@htclink.com, mobile 0932301478
公司介紹: 台灣上市資訊及通訊產品專業設計及生產公司
工作地點: 新北市
工作內容：
1. 設計、實作、測試與佈署Web application
2. 整合private cloud, public cloud, and 3rd party cloud所開放的API與服務
3. 與UX/UI合作進行系統流程與使用者經驗的優化
4. 新Web技術評估、整合導入

要求條件：
1. HTML5, CSS3, AJAX, PHP, MySQL, JavaScript, XML Web services, jQuery開發經驗： 3年以上
2. 運用Hadoop, MapReduce, noSQL, Machine Learning經驗： 2年以上
3. 熟以下至少一種Server技術 ： Ruby on Rails / PHP / Java / **Node.js**
4. 熟Python programming, Django framework and MySQL queries
5. 熟AWS, Azure, VM, Social Network API，REST API
6. 熟Git source control and continue integration and deployment
7. 熟Atlassian suite (Jira, Bitbucket, Bamboo, Confluence)或類似工具
8. 有應用docker技術經驗者佳
9. 英文聽說讀寫佳 (需與國外軟體團隊合作)

**Comment by dca** [comment]
```
根據 就業服務法 第5條第2項第6點，提供職缺之經常性薪資未達新臺幣四萬元，應公開揭示或告知其薪資範圍。
```

因內文未提及是否有符合，故先暫時關閉，有需要可以更新內文重開或另外新發，謝謝！

**Comment by junaldwang** [comment]
Dear,

Ok, Thanks for notice

Best Regards,
Junald Wang 王振榮



Dca <notifications@github.com> 於 2019年1月4日 週五 下午12:07寫道：
