### ISSUE TITLE
[徵才] 雲端技術軟體工程師-Backend x 1名

### ISSUE THREAD

**Issue by junaldwang** [nodejs-tw/jobs#116]
聯絡人: Junald Wang, email junald.wang@htclink.com, mobile 0932301478
公司介紹: 台灣上市資訊及通訊產品專業設計及生產公司
工作地點: 新北市
工作內容：
1. 設計、實作、測試後台服務與佈署
2. 整合private cloud, public cloud, and 3rd party cloud所開放的API與服務
3. 與UX/UI合作進行系統流程與使用者經驗的優化
4. 新Web技術評估、整合導入
5. API文件撰寫、與前端溝通協調

要求條件：
1. HTML5, AJAX, PHP, MySQL, JavaScript, XML Web services, jQuery開發經驗： 3年以上
2. 整合IoT與video processing實務經驗：2年以上
3. 熟JAVA, Java Script, **Node.js**, shell script, Python, Perl,
4. 熟Python programming, Django framework and MySQL queries
5. 熟AWS, Azure, VM, Social Network API，REST API
6. 熟RESTful API,
7. 熟Git source control and continue integration and deployment
8. 熟Atlassian suite (Jira, Bitbucket, Bamboo, Confluence)或類似工具
9. 了解大數據分析技術，有兩年以上運用Hadoop, MapReduce, noSQL, Machine Learning經驗
者佳
10. 有應用docker技術經驗者佳
11. 英文聽說讀寫佳 (需與國外軟體團隊合作)

**Comment by dca** [comment]
```
根據 就業服務法 第5條第2項第6點，提供職缺之經常性薪資未達新臺幣四萬元，應公開揭示或告知其薪資範圍。
```

因內文未提及是否有符合，故先暫時關閉，有需要可以更新內文重開或另外新發，謝謝！
