### ISSUE TITLE
【徵才】米達斯遊戲有限公司 - Node.js 工程師 (Koa 2, Socket.io, 年薪可達百萬, 可 remote)

### ISSUE THREAD

**Issue by osakihsieh** [nodejs-tw/jobs#119]
## 團隊簡介/地點

![](https://github.com/osakihsieh/feitu/blob/master/js%E4%BA%86%E4%B8%8D%E8%B5%B7.gif?raw=true)

Midas Gaming —— 取名自希臘神話中點石成金的米達斯國王
我們成立於2018年，專注在玩家對戰賽局遊戲自產研發，並有強大的市場團隊負責遊戲運營及推廣。
目前我們正在找尋優秀的前、後端工程師、遊戲製作人、美術人才，歡迎加入我們的團隊，一起讓夢想成真。

## 工作內容

- 使用 Node.js 開發撲克牌牌桌遊戲後端
- 規劃性能良好、語意優良的 API 及資料庫結構
- 有計劃地處理未來可能遇到的併發問題

## 能力需求

- Javascript
- Node.js
- Express.js 或 Koa2
- PostgreSQL 或 MySQL
- socket.io
- Git

### 加分

- 遊戲開發經驗
- Scrum 團隊經驗
- Markdown
- Clean Code

***

## 薪資範圍

**Junior**: 新台幣 4０,０００ 到 6０,０００ (十三個月) 年薪可達 **７８０,０００**
**Senior**: 新台幣 ８０,０００ 到 １００,０００ (十三個月) 年薪可達 **１,３００,０００**

## 工時/特休

- 09:30 ~ 18:30，中午休息時間 12:00 ~ 13:30
- 彈性上下班，唯十點需要 Stand-up meeting
- 除了法定的特休外，另外依照每個 sprint 完成進度給予多餘的特休

## 福利/推薦項

- 不定期聚餐
- 剛成立歡迎再討論

## 聯絡方式

- 請寄履歷到 aspdoctor@gmail.com
- 或到 [104 官網](https://www.104.com.tw/job/?jobno=6casc&jobsource=)投遞履歷

**Comment by explooosion** [comment]
這GIF好誘人啊~

**Comment by osakihsieh** [comment]
@explooosion 來吧來吧
