### ISSUE TITLE
[我們不一樣了] NOWNews 誠徵助理工程師 - Assistant Engineer

### ISSUE THREAD

**Issue by ghost** [nodejs-tw/jobs#12]
![Alt text](http://lazyfamily.twbbs.org/wewantyou.png)
## 公司簡介

NOWnews為台灣第一家網路原生新聞媒體，自2008年起創立專業網路新聞品牌後，不斷致力拓展「媒體大平台」概念，並搶在行動世代到來之際，結合行動裝置，陸續推出NOWnews Mobile Web、App、鬧嗨翻等；社群意識高漲，新媒體力量不容小覷，不僅掌握Facebook粉絲團互動經營，更率先與全球火紅即時通訊軟體LINE與WeChat合作，每日傳遞最新新聞訊息。在數位科技「One by One」掌握個人資訊來源即掌握意向的年代，NOWnews不斷創造先機，服務廣大閱聽眾。2013年7月，顛覆傳統，開創傳播無限可能，推出新概念紙媒「今日新聞報」，成為國內媒體O2O操作首例，整合線上及線下資源，希冀作為業界領頭羊，帶給各大企業與廣告主，在品牌行銷上新型態的服務選擇。

「NOWnews今日新聞」隸屬於今日傳媒股份有限公司。今日傳媒目前旗下擁有即時影音新聞網站「NOWnews」、最大公民新聞平台「WEnews」、線上影音購物「NOWshopping」等品牌。其中即時影音新聞網站NOWnews為目前台灣最大原生新聞內容提供者。合作夥伴包括：央視、Yahoo、 MSN、 Hinet、蕃薯藤、新浪網等，以及包括各大電信業者等知名公司。NOWnews除了擁有獨立的編採團隊外，並具備影音多媒體內容數位轉製，傳送各類通路平台（從網際網絡到平面及行動通訊）的專業技術與能力。因此，除了深耕新聞領域，也積極與各家平面、電子、網絡媒體業者進行跨領域合作。
## 工作內容
- 維護各子站台日常營運，包含程式除錯與開發新功能
- 協助開發新服務
- 協助開發新廣告型態
## 技能需求
- JavaScript 基本常識
- 會用 Git
## 加分(ㄒ一ㄣ)技能
- 熟 Node.js, Flask, Drupal
- 使用過 AWS 或是 Azure
- 使用過 python, go
- 使用過 Docker
- 知道什麼是 CI
- 跑過 scrum
- 參加過 conference 或是 hackathon(請準備作品)
- 其他作品(請提供 github, bitbucket 的連結)
## 薪資範圍

27000 ~ 無上限

依能力面議，目前平均薪資據說都有 40K 以上
## 真心話大冒險

NOWnews 的研發部正在處於重新編製的狀態，我們會使用大量的新技術，而且是「真責任制」，團隊相處愉快並且融洽，大家一起玩新技術，一起努力成長。

我們團隊不要求技術一定要頂尖，但是希望能夠有良好的溝通，並且一起努力的氛圍。
### 標題請打: `[我是超屌攻城獅 - 姓名]`

信的內容請簡單的介紹你自己，並且附上一份精美履歷給我們(或是個人網站)。

如果履歷是 111x, 1x4, yxs123 的制式履歷，我們一律已讀不回。

**Comment by dca** [comment]
ref https://github.com/NOWNews/jobs/issues/1

**Comment by dca** [comment]
@NOWNews 定期問一下，請問這個缺找到人了嗎？

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
