### ISSUE TITLE
[台北] Co-founder / CTO / Lead Blockchain / Crypto Engineer

### ISSUE THREAD

**Issue by regnregn** [nodejs-tw/jobs#123]
**Team Description/ Location**
We at Coinected.io are building the next global peer-to-peer marketplace for cryptocurrencies. Our platform utilize the power of blockchain and smart contracts to allow anyone, anywhere to easily buy and sell a wide range of cryptocurrencies with any local currency and payment method. Think of us as eBay for cryptocurrencies.

We are a young, dynamic and experienced team with roots from Europe and Asia. We are currently part of AppWorks 之初創投 Blockchain Accelerator in Taipei and at a pre-seed stage, finalizing our MVP.
We are looking for people with the right skills, mindset and drive to be part of our journey.

Location: Taipei City - https://goo.gl/maps/Y6xb8Lx9JSo

**What you will do:**
• Work closely with CEO & COO to determine the vision and roadmap for the platform
• Design system architecture and develop robust backend and microservices
• Take responsibility for development process, lead developers and collaborate with product owner
• Develop and audit blockchain related features - smart contracts, wallets, etc.
• Write high quality, reusable code, prevent vulnerabilities
• Maintain well-tested code base, implement and enforce good software engineering practices
• Code reviews

**Skills you will bring:**
• 3-5+ years of professional experience in software development
• 2-3+ years of professional experience in Node.js / JavaScript
• 1+ years of commercial experience in development of blockchain platforms or services (bitcoin, ethereum, smart contracts, Solidity, web3.js, wallets, exchanges, other blockchains etc.)
• Experience with design and development of highly scalable distributed systems and microservices
• Experience with design and development of REST APIs
• Good understanding of cryptography and security concepts
• Strong analytical, communication, problem-solving and entrepreneurial skills
• Attention to details, structured approach to work, emphasis on writing high quality, well tested code
• Ability and willingness to work in dynamic, fast-paced environment
• Startup mentality: willingness to wear many hats and strong desire to build the business from grounds up

You may also have:
• Experience in design and development of large-scale transaction systems and/or exchanges
• Angular 2/4 knowledge
• Experience with DevOps, web servers security

**Compensation**
• Competitive salary after funding/revenue
• Sweat equity proportional to your effort
• 30.000 - 600.000 NTD / Year

**We offer you:**
• Opportunity to build an exciting product with global reach and huge potential
• Freedom to make technical / design decisions and to implement your vision of development process
• Opportunity to have big impact on the product vision and the company
• Opportunity to get further commercial experience in development for many different blockchains / cryptocurrencies including, but not limited to Bitcoin and Ethereum
• Flexible hours - work at the office or from home
• Flexible holidays - Just ask
• Flat organization
• Transparent and open-minded company culture
• Co-founding opportunity

**Contact / Send CV**
Email: julius@coinected.io
LINE: julius..chang

**Comment by alincode** [comment]
30.000 - 600.000 NTD / Year ?

**Comment by regnregn** [comment]
Hi @alincode, yes. The wide range, because we are currently bootstrapped (only co-founder's own savings/money). So currently we have limited resources to pay more.
