### ISSUE TITLE
【誠徵後端工程師】泰德連橫有限公司

### ISSUE THREAD

**Issue by neojason** [nodejs-tw/jobs#13]
泰德連橫有限公司是泰德時代投資集團旗下的新創團隊，我們相信新技術帶來新的生活體驗，目前正在進行一項新計畫，希望能夠找到想法不受限的夥伴一起加入。  

我們預計要開發點對點去中心化的通訊系統。  

【公司名稱】泰德連橫有限公司/ Tidetime Union Limited  
【工作職缺】後端底層開發工程師 backend Developer1名  

【工作內容】  
負責開發即時通訊軟體所需的後端系統，包含  
- 帳號驗證與管理服務
- 檔案串流服務
- P2P protocol

【應徵條件】  

*_技術需求：  *_
- TCP/UDP 通訊實作  
- 對Socket技術相關了解  
- 熟悉開發noSQL資料庫

*_程式語言需求：  *_
Node.js 尤佳, Erlang, Go, Python 或其他程式語言亦可討論

*_學歷需求：  *_
computer science 相關科系  

*_工作需求：  *_
- 提供題目後，可以自行Research找出答案
- 英文文件的閱讀能力

*_其他需求：  *_
- 喜好使用檔案分享與交流相關軟體或平台
- 行動裝置的重度使用者
- 良好的溝通和理解能力與幽默感。

【加分項目】
- 熟悉 Amazon cloud service (EC2/S3/…)
- 熟悉Github

【工作地點與環境】  
- 敦化南路二段辦公大樓
- 定期補充各式零食（直接去店裡搬）

【工作時間】  
周一至周五 09:00~18:00(含午休1小時)  

【月休】  
周休二日  

【薪資範圍】  
年薪TWD 900,000-1,200,000  

【需求人數】  
1位  

聯絡人：Jackson Kuo  
email: jksnkuo@gmail.com  
phone: 02-27001979  

來信請寄至 < jksnkuo@gmail.com >  
信件主旨開頭請為：【應徵 Tidetime 後端 工程師】OOO (OOO 請用您的名稱取代之)。  
履歷或作品附件請用標準 PDF 檔案寄送。

**Comment by dca** [comment]
ref. #3

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
