### ISSUE TITLE
[徵才] 凱茂股份有限公司徵Node.js後端工程師

### ISSUE THREAD

**Issue by kamosoft** [nodejs-tw/jobs#131]
凱茂股份有限公司
www.kamo.com.tw

職務性質 | 全職
軟體設計工程師,Internet程式設計師
* [薪資] 優於市場平均薪資核定, 我們要的是『人才』, 而不是『人力』! (面議)
* [保險] 完全依政府法令規定, 絕不投機! 
* [休假制度] 勞基法怎麼訂, 我們就怎麼處理。BUT......我們額外提供『有薪生日假』:在您生日當月份, 任意找一天, 和親友慶祝狂歡一下!我們還提供了『有薪散心假』:每二個月, 您可以選一天, 出去走走, 讓身體也狂歡一下!
* [吃吃喝喝] 咖啡喝到飽! 冰塊吞到飽! 糖果餅干吃到飽!
 * [工作環境] 我們的公司還很小, 但我們的企圖心無限大!獨立的研發部門空間!開放式辦公空間! 可以讓四個成年人躺平的大辦公桌!透明的會議討論室!海島風格的Villa休閒區! 含L型沙發+懶骨頭!
* [家用設備] 微波爐! 電冰箱! 超強空調! 吸塵器 (咦!)
* [休閒設備] 蛤, 一堆電動? 3000合一超懷舊大型電動機台! 不爽就可以戰一下!PS4+VR：來場虛擬對打！Nintendo Switch：瑪莉歐、塞爾達大亂鬥！

* [這個職務的工作內容] 熟悉開發語言 Javascript。
熟悉 Nodejs。
熟悉 RDBMS 資料庫建立及維護。
熟悉 Unix Like 系統操作。
熟悉 Git 操作/版本管理。
熟悉 Google Cloud 相關部屬作業。
熟悉 Nginx 設定及建立。

擅長工具
PostgreSQL
JavaScript

有興趣者請跟我聯絡 -- 陳先生 andy@kamo.com.tw

**Comment by LIYINGZHEN** [comment]
為杜絕薪資面議，立法院院會今天三讀修正通過就業服務法部分條文，明定經常性薪資未達新台幣4萬元的職缺，雇主應公開揭示或告知求職者薪資範圍，違者最高罰30萬元。

**Comment by dca** [comment]
```
根據 就業服務法 第5條第2項第6點，提供職缺之經常性薪資未達新臺幣四萬元，應公開揭示或告知其薪資範圍。
```

因內文未提及是否有符合，故先暫時關閉，有需要可以更新內文重開或另外新發，謝謝！
