### ISSUE TITLE
☞擴編徵才-Senior Back-end Engineer

### ISSUE THREAD

**Issue by linettejhuang** [nodejs-tw/jobs#134]
#backend #Node.JS  #API  #RESTAPI #SQL #cloudservices
【Qualifications】
- ✔7↑ years  Back-end experience
- ✔Hands on experience working with Node.JS
- ✔REST API development experience is a plus.
- ✔Having experience working with cloud services is a plus.
- ✔Experience with different databases like PostgreSQL, MySQL  is a plus.
【Salary range : NT$ 1.5 - 2M】
If you are interested in this opportunity, pls send me CV and we will discuss further.
☎ +886-2-7721-8638#237
✉ linette.jhuang@talentplusco.com

**Comment by LIYINGZHEN** [comment]
為杜絕薪資面議，立法院院會今天(11/09)三讀修正通過就業服務法部分條文，明定經常性薪資未達新台幣4萬元的職缺，雇主應公開揭示或告知求職者薪資範圍，違者最高罰30萬元。

**Comment by linettejhuang** [comment]
Hi @LIYINGZHEN , 謝謝你的分享，開了這樣的條件肯定會優於這個薪資的不用擔心，不過我已經將薪資資訊編輯上去囉!
