### ISSUE TITLE
[徵才]奇卓科技Senior Web Developer

### ISSUE THREAD

**Issue by jennykuo0958** [nodejs-tw/jobs#135]
奇卓科技股份有限公司 http://www.androvideo.com/
AndroVideo是一家專注於前端AI智慧裝置的AIoT公司，在強大的前端硬體嵌入不同類型的AI算法，令攝影機擁有一顆聰明的大腦，進一步配合後台的資料整合，分析，算法進化等系統，BringAItoCamerathenLife。

我們看中的Android本身的平台普及性，開發者便利性，完善的AI處理效能支援以及系統本身的安全性，與世界大廠一拍即合，受世界大廠邀請加入OSSA聯盟（OpenSafetyandSecurityAlliance），打造消費者級的前端智慧攝影機配合服務，將AI應用更進一步的落實到日常生活中！

工作內容：
根據Prototype或Mockup開發嵌入Android的網頁

職務需求：
三年以上網頁開發經驗
熟悉JavaScript（ECMA6）或CoffeeScript
熟悉Node.js，了解非同步運作架構
熟悉React.js，了解React運作架構
熟悉的git

加分項目：
熟悉CSS，有辦法根據設計師的Mockup切版
熟悉Android NDK，可以使用NDK編譯C ++原始碼
請分享以前做過的專案，開源專案尤佳

薪資；
50~70K，將視能力與經驗核薪，可再議

歡迎連繫我們 jenny.kuo@abilitycorp.com.tw

**Comment by LIYINGZHEN** [comment]
缺薪資資訊
