### ISSUE TITLE
賭場管理WEB系統開發工程師 (Node.js)

### ISSUE THREAD

**Issue by GAMASYS** [nodejs-tw/jobs#14]
![gama](https://cloud.githubusercontent.com/assets/17841619/13941765/fba7ae4c-f025-11e5-8521-255516d8b608.jpg)

如果你~ 對撰寫程式充滿熱情
如果你~ 對接受挑戰樂此不疲
如果你~ 對開發產品充滿想法與創意
如果你~ 希望生活更加多采多姿

不要猶豫，加入我們的團隊，在充滿挑戰與激情的未來裡，
真誠的希望你會成為我們重要的夥伴，一起航向偉大的航道吧

**應徵時請附上Cover Letter(自薦信)，內容需含：
-自己的優勢及專長，為何覺得自己適合此職缺
-對公司的認識及瞭解**
## 薪資條件

1.學歷為學士，且軟體設計工作年資三年者底薪46K起，薪資詳談
2.學歷為碩士，且軟體設計工作年資二年者底薪48K起，薪資詳談
## 職務內容

1.撰寫賭場管理系統前端管理介面， 提升用戶體驗打造優異使用者介面
2.撰寫賭場系統包含帳務管理、會員管理與彩金管理
3.維護網站後端(Web Service)程式的開發、佈建、除錯及資料庫等
4.必要時需出差，協助國外賭場安裝系統
## 職務要求

1.熟悉 CSS、HTML5/ XHTML、JavaScript 開發
2.了解前端開發語言與架構(如jQuery、Bootstrap...等)
3.Responsive Web Design一年以上的實際開發經驗
4.具關聯式資料庫系統應用開發者
## 加分條件

1.熟悉Node.js並有實務開發經驗者尤佳
2.AngularJS等相關MMVM框架相關經驗者佳
2.具備軟體開發流程經驗，有Docker、Jenkins、CI/CD相關經驗者佳
3.有過Scrum經驗者佳
4.有UI或UX經驗與技能，前後端開發經驗者佳
## 聯絡方式

聯絡人：林小姐
信箱     : hr@gamasys.com.tw

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
