### ISSUE TITLE
【徵才】喬睿科技股份有限公司TapPay 徵 Backend Engineer

### ISSUE THREAD

**Issue by CherriHr** [nodejs-tw/jobs#160]
**團隊簡介/地點**

便利的世代更需彼此的信賴
我們是金融新創團隊喬睿科技，公司成立於2015年，並於2017年成為台灣首位Apple Pay整合廠商。

**我們的產品**
https://www.tappaysdk.com/zh/

**關於喬睿**
— 創立於2015年。
— 2017 年獲選KPMG 全球百大金融科技公司，同時也是台灣唯一入選的公司。
— 2018 年拓展香港、馬來西亞市場
— 2019 年開始拓展日本業務

銀行的風險管控服務是我們主打的產品，內容是打造國際組織EMVCo制定的交易機制，
並提供銀行進階的風險管控。
我們的團隊，使用新穎的科技，打造全新服務，這種沒有Legacy Code的環境，是不是很心動？
目前團隊還很年輕，文化與管理需要大家一同來經營。因而我們在尋找的，是一同分享工作時光的夥伴，一起成長。

如果你想尋找點刺激的，團隊有前電競選手，
下班後後相信也會有十足的成長。

我們深信藉由軟體來，我們能為台灣創造出我們自己的世代。

工作地點：台北市中山區南京東路二段69號7樓 （松江南京站出站三分鐘）

**工作內容**
1. 開發金流交易服務
2. 開發企業應用服務
3. 設計系統架構
4. 設計資料庫
5. 參與建造持續成長團隊

**能力需求**
1. 程式語言 Java / C# SQL (Oracle)
2. 具備資訊相關背景知識 
3. 物件導向分析與設計
4. 資料庫分析與設計 
5. 系統分析與設計
6. Spring 框架
7. 開發工具	
-Version Control: Git, SVN
-IDE: Eclipse, IntelliJ
-Build Tool: Gradle, Maven

**加分**

• 金流串接經驗 (第三方支付、金融交易 etc)
• CI/CD 流程 (Unit Test, Jenkin etc)
• 參加大型賽事 (星海天梯、 LOL 鑽石等級、運動賽事 etc)
• 熱情追求極致的事物 • 研究新知• Server管理部署 (Linux, AWS, Tomcat etc)
• 可以用英文開口點一杯奶昔外帶

薪資範圍
月薪 50,000元 ~ 80,000元
年薪保12個月，年終2~4個月不等

工時/特休
10:00~10:30 上班
18:00 下班
試用期過後即享七天福利假

福利/推薦項
◆ 不打卡彈性上下班 ◆ 員工旅遊 ◆ 咖啡飲料無限提供 ◆ 零食區 ◆ 年終獎金 ◆ 年度健檢 ◆ 明亮的辦公環境與休息區 ◆ 試用期過後即享七天福利假

◆ 配有Mac一台 ◆ 外接螢幕一台 ◆ 每人一張升降桌 ◆ 每週一下午茶時光 ◆ 每個月公司聚餐

聯絡方式
歡迎來信履歷跟github連結到：hr@cherri.tech

**Comment by yuanyu90221** [comment]
這個版 不是 以po nodejs為主嗎？
