### ISSUE TITLE
【徵才】【新北】Canner - 後端工程師 Backend Engineer

### ISSUE THREAD

**Issue by chilijung** [nodejs-tw/jobs#161]
## 工作內容
We’re looking for a backend engineer to work with us, Canner is a data management company, we accelerate Artificial Intelligence, Business Intelligence, and Big Data development and adoption for businesses.  Please check on our official site: https://canner.ai/. Before developing our data management product. Our company also actively contributed to open source community https://github.com/Canner, if you are an open-source lover and data enthusiast. Join us.

## 條件要求
What we’re looking for from you: 

- Independent, self-motivated 
- A smart and driven developer that is motivated to build a great product 
- Great communication skills and a desire to collaborate with the team 
- Deep experience with building web applications 
- An interest in taking on more responsibility and ownership over time

## Responsibilities: 
- Develop quality software and web applications 
- Analyze and maintain existing software applications 
- Design highly scalable, testable code 
- Discover and fix programming bugs

## Most important qualifications: 
- 2+ year of Typescript experience
- Familiar with CI/CD
- Familiar with GraphQL development (Apollo)
- Familiar with MongoDB, PostgreSQL

## 加分條件
- Familiar with Docker, DevOps

## 工作地點
新北市新莊區思源路 230 巷 35 號 8 樓

## 公司福利
- 到職第 1 到 3 年，享特休 14 日。 
- 到職第 4 年起，每年增加特休 1 日，到 30 日為止。 
- 兩月一次員工聚餐或活動。

## 薪資範圍
- 月薪 NT$ 60,000 以上依能力面議
- 保障年終獎金兩個月

## Contact
howard@canner.io

**Comment by appleboy** [comment]
500 https://www.cannercms.com/handle_github_callback?error%5Berror%5D=redirect_uri_mismatch&error%5Berror_description%5D=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error%5Berror_uri%5D=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&error%5Bstate%5D=27e3945df610436ba824

**Comment by chilijung** [comment]
> 500 https://www.cannercms.com/handle_github_callback?error%5Berror%5D=redirect_uri_mismatch&error%5Berror_description%5D=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error%5Berror_uri%5D=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&error%5Bstate%5D=27e3945df610436ba824

good catch! Will check with the team tomorrow to fix it. Thanks!

**Comment by appleboy** [comment]
@chilijung I can't login with Google or GitHub. Please also check the google login.
