### ISSUE TITLE
「徵才」「新北」承豐善澤 Harvirtue - 後端工程師 Back-End Developer

### ISSUE THREAD

**Issue by yenming** [nodejs-tw/jobs#166]
## 團隊簡介
秉持給消費者更好的產品，給廠商更好的利潤為原則，尋訪更好的產品項目，為產品經營完整的銷售平台，達到消費者與廠商的雙贏局面。經營實體電商，並結合線上與線下整合概念，配合區域性快速配送。以實現『不用出門即可購物，出了門依舊可以輕鬆購物』之理想零售型態。
##  上班地點
新北市新莊區民安路319巷8號
## 工作內容
<ol>
  <li>Nodejs api維護與開發</li>
  <li>資料庫設計與維護</li>
  <li>Google/AWS Server規劃與維護</li>
</ol> 

## 能力需求與條件

<ol>
  <li>心理素質強</li>
  <li>良好的溝通、表達、理解能力</li>
  <li>遵循團隊開發風格</li>
  <li>2 年以上開發工作經驗</li>
  <li>熟悉 Node.js</li>
  <li>熟悉 Express/Koa</li>
  <li>具有 Unit Testing 經驗</li>
  <li>具有 Git 相關版控工具使用經驗</li>
  <li>具有任一資料庫使用經驗 PostgreSQL / MySQL / MariaDB</li>
  <li>熟悉關聯式資料庫或 NoSQL 資料庫</li>
</ol>  

## 加分條件

<ol>
  <li>曾經參與大型專案</li>
  <li>具有 DevOps 經驗</li>
  <li>熟悉 MongoDB</li>
  <li>熟悉 CI, CD 概念</li>
  <li>熟悉資料庫效能調校</li>
  <li>熱衷參與技術相關論壇或社群活動</li>
</ol>

## 薪資範圍

<ul>
  <li>年薪60萬至100萬</li>
</ul>

## 工時/特休

<ul>
  <li>工時：09:30 ~ 18:00</li>
  <li>特休：依照勞基法</li>
</ul>

## 福利

<ul>
  <li>不定時聚餐</li>
  <li>每月午餐經貼</li>
   <li>學習新技能補貼</li>
</ul>

## 聯絡方式

來信請寄 service@harvirtue.com，並除履歷基本資料外，請提供github連結。

## 其他職缺

website: https://harvirtue.github.io/jobs/

**Comment by dca** [comment]
哥賞口飯吃啊

**Comment by yenming** [comment]
卡大 我需要靠你才是XＤＤD
