### ISSUE TITLE
[徵才] 遠端全端開發（Node.js為主）

### ISSUE THREAD

**Issue by wahengchang** [nodejs-tw/jobs#177]
## 團隊簡介/地點
我們是海外正在孵化的新創團隊，產品是B2B AI 影像識別，以香港、澳門市場為主。目前正尋求長期合作的全端開發人員，期望每天可投入 2-3 小時的時間，開發一些小工具（網頁和 bash script為主）。

## 內容
 - script 開發（可能是bash、python 或 node.js）
 - 網頁開發
 - 新技術評估
 - 技術文件整理
 - DNS 設定

求職者可以是旅行中，或者是在家工作的朋友。
我們不介意提案者的年齡、學歷，我們關心的是工作能力和態度。因為是遠程工作，所以對溝通和會議時間的要求更高。溝通的工具會以 git, google drive 為主。

## 工時/特休
週一至週五 - 彈性工作時間（大約每天投入 2-3 小時）
（但固定的 daily meeting 必須準時參與）

## 薪資範圍
預算 $2-8萬（視能力而定）

**Comment by owlfox** [comment]
Hi, 
請問可以提供公司資訊/聯絡方式嗎

**Comment by wahengchang** [comment]
email: peterchang@golding.cc

**Comment by wahengchang** [comment]
@owlfox

**Comment by sharils** [comment]
Hi @wahengchang  - Is this still open?
