### ISSUE TITLE
誠徵Full-stack/Front-end JS developer 全端/前端工程師 - 愛文西門科技

### ISSUE THREAD

**Issue by coold8d** [nodejs-tw/jobs#18]
大家好! 我們是台灣的新創團隊sivann。
sivann是一個有理想有熱情的新創公司，我們的願景是打造一個前瞻性的Open Fast-prototyping IoT Framework (開源式物聯網軟硬體整合平台與解決方案)，不同於其他雲端物聯網平台公司，我們重新定義了IoT應用的快速開發方式，並處理了複雜的異質網路互通性問題。為了加速台灣物聯網產業的發展並能快速與世界接軌而努力，需要各方好手的加入。
你也想加入一個具有挑戰性又能影響全世界的新創物聯網開發團隊嗎?
Location: Neihu-Taipei Type: Full-Time - Department: Engineering
Job Requirements:
熟悉Javascript與Node.js
有 MEAN stack 之經驗
有 websocket messaging 之開發經驗佳
Plus:
通 React.js 佳
有使用 RESTful 經驗
略通嵌入式系統佳
對開發物聯網應用有高度熱忱
對硬體/韌體開發與各種通訊協定有經驗或興趣學習者尤佳

請email至ivan.chang@sivann.com.tw
公司網站
http://www.sivann.com.tw/contact-us.html

**Comment by goden** [comment]
抱歉 因為沒有住址，所以我找查了一下。
請問**愛文西門科技**是位於內科陽光街嗎?
想跟您確認一下!!

**Comment by coold8d** [comment]
是，我已經加上公司網頁連結。
可以參考這裡，
http://www.sivann.com.tw/contact-us.html
