### ISSUE TITLE
後端工程師

### ISSUE THREAD

**Issue by F23ko** [nodejs-tw/jobs#2]
徵人，現在有兩個主要職缺。

1. IOS開發
. 請用原生開發，聽說IOS8之後語言換用 swift
2. 以TCP/IP為基礎的API開發
. node.js 或 java 或 C#，語言會其中一種即可

加分副技能（非必須）
1. 網頁相關(一種後端語言、javaScript、html、css)
2. node.js
3. android 原生開發
4. ios 原生開發
5. 第二種熟悉的程式語言，例如java php c# javascript ruby python perl

薪水30k~60k，獎金一年兩次，每次保證一個月
彈性上下班時間，一天九小時上滿自動下班，最晚下午兩點前到公司
詳細的工作內容以及福利，連絡我之後，連絡我之後會告訴你
.
地點：台中
連絡方式 mayasunzlight@gmail.com

**Comment by dca** [comment]
請問這個已經找到人了嗎?

**Comment by F23ko** [comment]
已經徵到了，謝謝。

**Comment by dca** [comment]
@F23ko 那就先關閉囉
