### ISSUE TITLE
Web Developer (Full stack)

### ISSUE THREAD

**Issue by junaldw** [nodejs-tw/jobs#20]
這家公司福利:
- 薪資優，免打卡，工時正常，朝十晚六，午休一小時 
- 員工旅遊，不定時聚餐、勞健團保
- 第一年即享特休十天

我的聯絡資訊: Junald Wang
Mobile 0932301478
Email junald.wang@htclink.com

Senior Web Developer (Full Stack), 工作地點: 台北市內湖
[工作職掌]
# 負責網站開發, 包括分析、設計以及程式撰寫，熟悉軟體測試與修改

[要求條件]
3年以上相關工作經驗
熟悉後端 Node.js及相關framework (ExpressJS)
熟悉前端 jQuery / jQuery Mobile(RWD) / Javascript / HTML5 / Bootstrap
了解 MongoDB 運用
可獨立或與團隊成員合作，並具備良好的溝通與傾聽技巧

**Comment by appleboy** [comment]
這裡面有三個職缺，要不要拆開寫啊，我第一次進來看到還以為一個人要 16 個技能 XD

**Comment by junaldw** [comment]
Appleboy: 改好成不同的兩個issues, 拿掉UI Designer(不是node.js的範疇)， 謝謝你的提醒
