### ISSUE TITLE
[徵才] 新加坡服務業新創Boxcar Digital | 全職Full-Stack Software Engineer (Backend)

### ISSUE THREAD

**Issue by ozfan** [nodejs-tw/jobs#209]
大家好，我們想尋找1位Full Stack Software Engineer (Backend)加入我們台灣的產品團隊。
我們是一家新加坡初創，我們的目標是做新時代的招聘體驗，不管是兼職或全職工作。我們的產品提供給尋找工作的人一個更可以發揮他們創意和個性的渠道來連結適合的僱主。

We're looking for a Full Stack Software Engineer (Backend) to join our product team in Taipei.
We are a dynamic startup based in Asia operating in Taipei and globally with a vision to revolutionise the job marketplace. Our product enables job-seekers to express their creativity and individuality to employers and recruiters in a post-COVID world. We’ve reimagined the job-search process with humanizing technology, offering a modern way that candidates and employers can present themselves through visual and auditory mediums. Mediums that make the job-seeking process fair, efficient, and dare we say, fun; as opposed to the monotonous, tired ways of recruiting. 

Our team’s expertise in technology, marketing and entrepreneurship has enabled our startup to form and strategise this vision. To complement our expertise, we’re looking for talented and ambitious developers to join our technology and product team in Taiwan for this new adventure!

We are looking for a highly skilled full stack developer who is specialized in frontend to build performant mobile apps on both the iOS and Android platforms. You will be responsible for architecting and building these applications, as well as coordinating with the teams responsible for other layers of the product infrastructure. Building a product is a highly collaborative effort, and as such, a strong team player with a proven track record of delivering applications as part of a remote / distributed team is required.

**Responsibilities**

- Architect, build, and maintain excellent Node.js applications with clean code
- Design and construction of our API
- Collaborate with frontend developers on combining their frontend elements and components with the server-side
- Write high quality, readable and testable code
- Design and optimize applications for high performance, high scalability, high security, and low latency

**Qualifications & Requirements**

- 4+ years experience building applications with Javascript
- Familiar with fundamental frontend technologies such as HTML, CSS, and JavaScript
- Proficiency with Node.js, Express, and the most common packages in the ecosystem
- Proficiency with database technologies such as PostgreSQL and MongoDB
- Proficiency with accessibility and security compliance, user authentication, and authorization between multiple systems, servers, and environments
- Proficiency with code versioning tools, such as Git
- Experience in software engineering practices, including but not limited to software design and implementation, unit testing, code reviews, continuous integration, source control, and coding standards compliance
- Excellent communication skills in English
- Self-motivated, responsible, good attention to detail
- Decision-making, problem resolution, and creative thinking skills

**Salary**
80,000 - 150,000 NTD/month (dependent on skill and experience)

If you're interested, please apply directly here or contact ivan@brandmotor.com, thanks! Please check out this link for more info: [Full Stack Software Engineer - Backend](https://www.cakeresume.com/companies/brand-motor/jobs/full-stack-developer-backend)

**Comment by sharils** [comment]
Hi @ozfan  - Is this still open?

**Comment by ozfan** [comment]
Hi,

Thank you for your interest! However this position is now closed.

Best,
Ivan

**Comment by sharils** [comment]
Hi @ozfan - Would you mind close this issue then?

**Comment by ozfan** [comment]
> Hi @ozfan - Would you mind close this issue then?

Yes, will close now. Thank you.
