### ISSUE TITLE
【外商】 徵Sr. Node.js Backend Engineer 1.3M

### ISSUE THREAD

**Issue by SearchAsia** [nodejs-tw/jobs#22]
1. 使用Node.js進行伺服器後台開發 
2. 熟悉 Node.js NPM開發環境 
3. 熟悉 Express.js Web and RESTful API 開發框架 
4. 熟悉基本軟體工程開發套件，包括Git，bug issue tracking
5. 熟悉雲端AWS或Azure App服務建置尤佳
6. 熟悉MongoDB或DocumentDB串接尤佳

Jon Lee
Email: jon.lee@searchasia.com.tw

**Comment by dca** [comment]
請問 #21 #22 是同一個還是不同的呢？

**Comment by SearchAsia** [comment]
Hi Dca，

兩個是不同的公司！
都是要backend node.js要求有一些不同，加上一家薪水有範圍，另一家看實力多少都能談，所以分2則po，如果覺得不妥，下次我會盡量合併成一個issue。

謝謝您！


Best Regards,
                       Jon

**Comment by dca** [comment]
@SearchAsia 沒關係的，不同的職缺分開很好 👍 。  只是我覺得大家會跟我有一樣的疑問，所以就先問了
