### ISSUE TITLE
Front End Web Developer

### ISSUE THREAD

**Issue by junaldw** [nodejs-tw/jobs#23]
這家公司福利:
- 薪資優，免打卡，工時正常，朝十晚六，午休一小時 
- 員工旅遊，不定時聚餐、勞健團保
- 第一年即享特休十天

我的聯絡資訊: Junald Wang
Mobile 0932301478
Email junald.wang@htclink.com

Front End Web Developer
工作地點: 台北市內湖
[工作內容] 
公司網站維護
開發與維護靜態/jQuery(動態)頁面 
介面 Wireframe設計製作 
[要求條件]
1年以上工作經驗 
熟悉  jQuery / jQuery Mobile(RWD) / Javascript / HTML5 / Bootstrap / CSS 
開發網站介面與前端程式(jQuery/jQuery Mobile)撰寫, 並須能與後端資料銜接
可獨立或與團隊成員合作，並具備良好的溝通與傾聽技巧 
[加分] wordpress / Material Design Lite / Git / NodeJS

**Comment by jsgao0** [comment]
有公司簡介和薪資範圍會更好哦~
