### ISSUE TITLE
[Banana Whale Studios] JavaScript Developer

### ISSUE THREAD

**Issue by bananawhale-HR** [nodejs-tw/jobs#28]
Banana Whale Studios 香蕉會兒設計工作室
創立於2016年3月，創始團隊擁有超過30年跨國際的產業經驗
致力於遊戲,網頁及商用平台的設計和開發，用最新的技術帶給玩家更好的體驗
內容是我們的決戰關鍵，創新是我們的不敗法門

Responsibilities

網站前端介面開發維護 Website Frontend Development
開發流暢體驗的行動版網頁 Responsive Design
遊戲客戶端開發維護 Game Client Development
後端系統整合 Backend Integration
產品效能最佳化 Performance Optimization

Requirements

專業負責，與團隊共同達成目標
熱衷於學習分享新技術，找到更好解決問題的方法
精通網頁前端技術，了解遊戲製作流程
熟悉 JavaScript 語言的設計框架，例如 React、Flux
熟悉 HTML5/CSS3
熟悉 Google Chrome DevTools 或其他前端開發工具
熟悉 Version control tools，例如 Git 
加分 NodeJS，TypeScript，MVC/MVVM架構，及跨平台開發及上線經驗

Benefits

國際化的工作環境，與外國客戶與團隊合作
敏捷式開發流程，團隊由下向上自主管理
自由開放的工作文化，歡迎任何讓我們進步的意見
保障年薪13個月，未來依公司獲利分紅
彈性上下班，彈性休假

email us at: hr@bananawhale.com

**Comment by ritatmliu** [comment]
Banana Whale Studios 香蕉會兒設計工作室
創立於2016年3月，創始團隊擁有超過30年跨國際的產業經驗
致力於遊戲,網頁及商用平台的設計和開發，用最新的技術帶給玩家更好的體驗
內容是我們的決戰關鍵，創新是我們的不敗法門

Responsibilities

網站前端介面開發維護 Website Frontend Development
開發流暢體驗的行動版網頁 Responsive Design
遊戲客戶端開發維護 Game Client Development
後端系統整合 Backend Integration
產品效能最佳化 Performance Optimization

Requirements

專業負責，與團隊共同達成目標
熱衷於學習分享新技術，找到更好解決問題的方法
精通網頁前端技術，了解遊戲製作流程
熟悉 JavaScript 語言的設計框架，像是 React、Redux
熟悉 HTML5/CSS3
熟悉 Google Chrome DevTools 或其他前端開發工具
熟悉 Version control tools，例如 Git
加分 NodeJS，TypeScript，MVC/MVVM架構，及跨平台開發及上線經驗

Benefits

國際化的工作環境，與外國客戶與團隊合作
敏捷式開發流程，團隊由下向上自主管理
自由開放的工作文化，歡迎任何讓我們進步的意見
保障年薪13個月，未來依公司獲利分紅
彈性上下班，彈性休假

email us at: ritaliu@bananawhale.com
