### ISSUE TITLE
[Hahow線上教學平台] 徵Backend Engineer

### ISSUE THREAD

**Issue by danielscw** [nodejs-tw/jobs#29]
🎓  大家好，我們是 [Hahow好學校](https://hahow.in) 是一個結合募資概念的線上課程平台，目前已經累積了上萬名的付費使用者、待開發的系統功能也已經塞不下 Trello 的 Board。因此為了能夠更快滿足使用者的需求、同時加速整個教學分享社群的成長，Hahow開始徵求新的工程師夥伴加入，一起透過精實創業的精神、敏捷開發的思維以及捨我其誰的態度，翻轉台灣的教育！💪💪💪
## 工作內容
- 網站API開發與維護
- 第三方服務（郵件、客服等）系統整合
- 協助伺服器維護與管理
## 主要會使用到的工具
- Cloud Platform有使用Google Compute Engine, Google Cloud Storage
- CI/CD使用Jenkins搭配Docker
- API Server使用Nodejs, Expressjs搭配MongoDB
## 工作要求
- 熱愛學習與分享，享受新創團隊充滿挑戰性的生活
- 具有廣度興趣，熱愛接收新鮮事物，能跟各領域人才交流學習
- 個性活潑、積極與健談，抗壓性高，且有工作熱忱
## 必備條件
- 熟悉NodeJS (ExpressJS)
- 熟悉MongoDB (Mongoose)
- 曾經有開發Restful API的經驗
- 熟悉Git
## 加分條件
- 有NodeJS testing (unit test, integration test)的經驗
- 熟悉Git flow開發模式
- 熟悉Command Line，習慣使用*nix系統
- 使用過Google Compute Engine, Google Cloud Storage
- 使用過Docker
- 有設定Jenkins CI/CD的經驗
## 薪資福利
- NT$ 50,000 至 NT$ 75,000（實領月薪，公司會另外保勞健保與勞退）
- 特休一年15天，每一年多一天
## 工作地點
- 南京東路三段223巷8號6樓（南京復興捷運站走路5分鐘）
## 應徵方式

將相關資料，包含：
- 可以展現個人特色的履歷
- 個人Github頁面
- 跟此工作內容有關連的任何作品集
- 寄送至 talent@hahow.in，我們將儘快回覆，採隨到隨審制度

其他職缺可參考 http://blog.hahow.in/engineer-recruiting/

**Comment by jsgao0** [comment]
很棒的共享平台!

**Comment by austintodo** [comment]
Hello 各位好，我是 Hahow 的工程師，2016.10 新增 Node JS 後端職缺，詳細的徵才資訊可以到 [http://hahow.in/joinus](https://hahow.in/joinus ) 查詢
