### ISSUE TITLE
泰德連橫 - 誠徵後端底層開發工程師 (Backend Developer)

### ISSUE THREAD

**Issue by neojason** [nodejs-tw/jobs#3]
職務分類：網頁程式設計師

工作地點：敦化南路二段辦公大樓

薪資範圍： NT$ 70,000 - NT$ 100,000

泰德連橫有限公司是泰德時代投資集團旗下的新創團隊，我們相信新技術帶來新的生活體驗，目前正在進行一項新計畫，希望能夠找到想法不受限的夥伴一起加入。

我們思索如何能夠提供真正的雲端儲存空間，釋放用戶端的空間；透過我們的平台，讓User的閒置空間，能夠轉換成出租儲存空間，猶如線上的Airbnb，同時也持續開發相關服務，期待提供更有意思的儲存服務。

【工作內容】
協同開發P2P的運算平台，串連所有裝置的運算資源，
提供高可用性的服務供各項應用程式使用。

【應徵條件】

技術需求：
software raid
p2p protocol
distributed computing
transport layer security
data encryption

程式語言需求：
node.js 3年以上經驗

學歷需求：
computer science 相關科系

工作需求：
可協同或主導討論相關演算法設計或改良
可針對軟體瓶頸提出優化方針
具備 prototype 實作能力
開發 library 需支援 Mac, Linux, Windows 64位元 及 32位元環境

其他需求：
喜好使用檔案分享與交流相關軟體或平台
行動裝置的重度使用者
良好的溝通和理解能力與幽默感。

【加分項目】

熟悉 Amazon cloud service (EC2/S3/…)
熟悉Github

【工作地點與環境】
敦化南路二段辦公大樓
定期補充各式零食

【工作時間】
周一至周五 09:00~18:00(含午休1小時)

【月休】
周休二日

【需求人數】
1位

聯絡人：Jackson Kuo
email: jksnkuo@gmail.com
phone: 02-27001979

來信請寄至 < jksnkuo@gmail.com >
信件主旨開頭請為：【應徵 Tidetime 後端 工程師】OOO (OOO 請用您的名稱取代之)。
履歷或作品附件請用標準 PDF 檔案寄送。

**Comment by dca** [comment]
請問這個已經找到人了嗎?

**Comment by neojason** [comment]
Still finding, you can send me your resume. Thanks!

 sent from the mobile device

**Comment by dca** [comment]
ref #13

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
