### ISSUE TITLE
台灣大數據誠徵 NodeJS 工程師

### ISSUE THREAD

**Issue by dreamerhyde** [nodejs-tw/jobs#32]
## 一、職缺說明

職稱：
- NodeJS 工程師

工作內容：
- 使用 Node.js 撰寫提供 Web、Mobile App 使用之後端程式
- 依專案需求撰寫 API 參考文件

工作條件：
- 熟悉 Node.js 開發環境
- 熟悉 Express / Socket.IO
- 熟悉 JavaScript / ECMAScript 6
- 熟悉 MongoDB / MySQL / PostgreSQL 其中至少一項
- 熟悉用 Git 與團隊協作
- 熟悉 SCRUM
- 注重團隊精神，可以和研發夥伴溝通、配合

加分：
- 對技術非常有熱誠
- 熟悉前端框架 Bootstrap / ReactJS / AngularJS
- 熟悉測試案例撰寫
- 熟悉 Jenkins CI
- 熟悉其他自動化工程工具
- 自己有在寫技術性的 Blog
- 提供你的 Github 帳號供我們參考
- 提供你的書單
- 提供你平常關注的網站、Blog

**工作地點：**
- 台北市中山區龍江路305巷16-1號1樓（近中山國中捷運站，走路5分鐘）

上班時間：
- 約 10:00~18:00 （彈性工時，可自己調整上下班時間）
## 二、待遇及福利
- 薪資待遇：面議
- 獎金制度：公司會依照產品業務發展狀況提供額外獎金（年終 / 績效）
- 爽爽環境：提供開發者專用頂級 Dell 螢幕、舒適的人體工學辦公椅及舒適的工作環境，咖啡飲料/零食/紅酒無限量供應。另外，公司有個美麗的庭院與 Costco 大型烤肉架，所以時常會舉辦烤肉 Party（享有 Bose 音響、紅酒、~~美女~~）
- 休假多多：周休二日，台灣見紅字就放假，國外節日也放假（如聖誕節，公司有美國同事）
- 語言學習：公司有美國同事於每週五舉辦英語教學課程，強化國際化能量

履歷請寄到 【hr@bigdata.com.tw】，標題【應徵 Node.js Engineer - 姓名】
## 三、公司簡介

台灣大數據分析股份有限公司（Taiwan Bigdata Inc.）是一家專注於物聯網（IoT, Internet of Things）、大數據（Big data）及雲端（Cloud）解決方案的公司， 詳細介紹請參考公司官方網站： https://bigdata.com.tw/
## 其他職缺

[Android / IoT 工程師](https://gist.github.com/dreamerhyde/bbbdd4dc484e6402285510ef7f8be4f6)

**Comment by SimonSun1988** [comment]
幫忙推一下，裡面好棒棒可以烤肉唷

[Imgur](http://i.imgur.com/QM2wB66.jpg)
