### ISSUE TITLE
[Sudo Recruit] 美國Developer職缺 (JS/node.js)

### ISSUE THREAD

**Issue by henrychongtw** [nodejs-tw/jobs#34]
https://www.facebook.com/sudorecruit/posts/1191283714225979

**Comment by IvanWei** [comment]
這內容偷懶就算，效果也沒有 PO FB 來得好，FB 至少可以看到內容=3=

**Comment by PolarBearAndrew** [comment]
* 沒有對方公司的聯絡資料
* 主要聯絡方式為 Sudo

@dca  這個 issue 應該可以 close 了

**Comment by dca** [comment]
@PolarBearAndrew 感謝提醒！

**Comment by clonn** [comment]
因 sudo 已經對外宣告停止，將此 issue close
https://www.facebook.com/sudorecruit/posts/1292797517407931
