### ISSUE TITLE
[台南][短期]徵求Node.js工程師一名

### ISSUE THREAD

**Issue by bucky0970** [nodejs-tw/jobs#35]
要跟朋友成立一間設計公司，有些工作上的需要，要使用Node.js中的一個module，但是本人跟朋友都沒有碰過這塊。
可能需要您幫忙架設環境，並教我如何維護！
只要架設到可以正常執行到我可以自行維護就可以～（預計10小時)
待遇方面以時薪計（其他計價方式都可以談），可以利用假日時間來教我跟架設。
細節請與我聯絡：bucky0970@gmail.com

**Comment by SimonSun1988** [comment]
有沒有更詳盡的內容呢?
