### ISSUE TITLE
[CHOCOLABS(歐酷網路)] 誠徵 NodeJS 後端架構工程師

### ISSUE THREAD

**Issue by chocolabs-jobs** [nodejs-tw/jobs#37]
## **公司簡介**
台灣最大 APP 品牌發行商 & 行動新媒體 - CHOCOLABS 

CHOCOLABS (歐酷網路) 台灣出發最頂尖的 APP 品牌發行商，致力打造行動新媒體的全新體驗及數據整合。團隊擁有「自主研發 APP 產品、推廣發行自有品牌、專屬廣告業務團隊、大數據決策強化」等 APP 產業完全整合能力。打造包含 iMusee、電視連續劇2、YouBike 讓我騎、10 秒讀新聞等知名產品，累積超過 1,200 萬下載及每月 180 萬活躍使用者，為台灣 APP 領導品牌！ 

「CHOCOLABS」一詞由 chocolate 和 lab 組成，結合 chocolate 軟性甜美的印象，讓歐酷網路的 APP 品牌不只是單一的科技元素，訴諸女性使用者，打造品牌故事。透過 lab 的無限創意 & 堅強研發能力，持續尋找市場下個爆發的機會點，創造食衣住行育樂多方面的「優質APP」品牌形象，CHOCOLABS 願景是成為華人世界第一的 APP 品牌!

## **工作內容**
1. APP產品後端功能開發、設計、測試、維護
2. APP產品內容編輯網站開發、設計、測試、維護
3. 與PM、前端工程師溝通規劃專案進行方式與時程

## **工作技能**
1. 熱愛打造APP產品、有很多想法，對於創業或 Startup 有熱情
2. 渴望成長、擁有想要改變世界的野心
3. 具備良好團隊合作 & 溝通能力，對於新技術與寫程式具有高度熱忱
4. 熟悉 Node.js / ECMAScript 6
5. 熟悉 Node.js相關 module/framework 例如Express / Koa
6. 使用Git
7. 具備MySQL / MongoDB使用經驗

## **加分條件**
1. 使用Git
2. 具備資訊安全背景知識
3. 寫過爬蟲
4. 熟悉AngularJS / ReactJS
5. 經常自發性參與開發者社群活動
6. 具備使用Mocha 撰寫測試相關經驗
7. 接觸過CI Server 例如 Jenkins等

## **公司福利**
● 到職首年即享有 10 天特休假，每滿一年加一天
● 女性同仁每月一天生理假 (全薪)
● 員工專屬生日假、生日禮
● 每季一次的員工 Outing
● 電腦設備購買補助
● 員工健檢補助
● 每周五下午固定 Happy Hour
● 備有零食櫃
● 產品團隊聚餐
● 同仁生育補助
● 產檢假、陪產假 8 天 (全薪)
● 婚假 10 天 (全薪)

## **薪資範圍**
依經驗與能力面議

欲應徵請將履歷和作品E-mail至 jobs@chocolabs.com
（標題請註明: [應徵] 後端架構工程師 (Node.js)）
或至 https://www.104.com.tw/job/?jobno=4qs8i&jobsource=

**Comment by honomoa** [comment]
四個月前寄信被無視了...
