### ISSUE TITLE
Startup is asia

### ISSUE THREAD

**Issue by jamjamlong266** [nodejs-tw/jobs#38]

**Comment by jamjamlong266** [comment]
looking for a developer and partner to scale up our web services, currently we had the MVP up and running. There is more features to add on, hope you cloud join in and we can scale the company to next level.

contact me at jamjam@jaminpie.me

**Comment by IvanWei** [comment]
Hi @jamjamlong266 

I can't look for information of this job. Workplace? Job description? Salary?
