### ISSUE TITLE
【泛科知識】誠徵 Node.js 工程師

### ISSUE THREAD

**Issue by mrmu** [nodejs-tw/jobs#40]
這裡有一群喜歡挑戰並樂於學習新技術的同伴們，如果你樂於團隊合作，喜歡分享技術經驗，我們期待您的加入，並成為團隊成長的催化劑。
## 公司簡介

PanMedia是台灣最大的新媒體集團，旗下擁有科學、科技、娛樂等產業之垂直媒體，透過整合性的數位媒體服務，提供最佳的行銷效益 。 

1.PanSci 泛科學（pansci.asia）是國內科學最大的科學社群及知識社群行銷的領導品牌。 

2.PanX 泛科技 (panx.asia) 聚焦全方位科技發展、創新創業、產業應用、科技生活，結合 PunNode、PunApp、MakerDIWO 三大知名垂直網站，將科技對未來的影響做最深入、最完整的覆蓋。

3.Punchline 娛樂重擊（punchline.asia)是台灣影視音娛樂產業介接新科技媒體的垂直媒體，在創新的變動中媒合娛樂產業的新模式。 同時經營流行音樂主題站 Taiwan Beats(taiwanbeats.punchline.asia)

PanMedia集團與Wavenet潮網科技集團為關係企業，潮網科技(wavenet.asia)為Facebook在台灣及中國的廣告技術整合服務商，客戶涵蓋南方航空/中興通訊/吉利汽車等，為企業提供Facebook全球性行銷最優勢的廣告投放策略及服務。潮網統整集團豐富的媒體資源，以自行開發的RTB/DSP系統，致力帶給廣告主最精準投放，在新媒體時代，創造數位廣告行銷的最大綜效。目前集團服務據點涵蓋英國、美西、香港、台北、上海、北京、廣州、深圳。 

如果您主動積極、負責、熱愛新媒體，習慣或正在培養「解決問題」的思考方式，我們想要找到未來能長期一起奮鬥的夥伴，與PanMedia一起抓住日新月異的新媒體脈動，共創行銷效益，成為改變科學與科技的新力量。
## 工作內容
1. 使用Node.js進行軟體開發，包括分析、設計以及程式撰寫。
2. 開發與維護自有產品，如: 活動票券平台、會員數據系統。
3. 熟悉 Node.js、 NoSQL (MongoDB, Redis) 或 SQL (MySQL, PostgreSQL)
## 加分條件

1.Unit Testing 經驗
2.DevOps 經驗
3.熟悉資料庫效能調校
4.熟悉 Express/Koa
5.熟悉 React.js、AngularJS 等前端框架
## 應徵方式

欲應徵請將履歷和作品E-mail至 audilu@panmedia.asia
（標題請註明: [應徵] Node.js 工程師）

或利用 104 人力銀行：
http://www.104.com.tw/job/?jobno=51ivp&jobsource=open&hotjob_chr=

**Comment by PolarBearAndrew** [comment]
@dca  職缺已在104關閉
