### ISSUE TITLE
國際級生物指紋辨識系統研發製造先驅 - 「Sr Nodejs工程師」

### ISSUE THREAD

**Issue by SimpsonAllen** [nodejs-tw/jobs#44]
19件發明專利科技產品應用，獲得海內外市場肯定。 近期積極發展創新軟體技術開發，將更廣泛應用於“醫療、長照” “電商、支付” 領域。

職務&條件：
- 依需求規劃npm功能。各項產品功能npm開發
- npm自我測試、回報結果工具撰寫
- 程式發佈、自動更新流程
- 依需求規劃撰寫單元測試
- 依設備提供dll撰寫對應extension
- 實作OAuth, FIDO, Third驗證流程 [或對此相關技術感興趣，公司有意訓練]

薪資範圍：
*優渥薪資80K~120K/月

應徵方式：
履歷寄至 bruce@smartm.com.tw

**Comment by IvanWei** [comment]
[星友科技股份有限公司](http://www.1111.com.tw/job-bank/company-description.asp?nNo=2765071) 的職缺
