### ISSUE TITLE
全台最大APP品牌發行商 & 行動新媒體 - 「Sr / Node.js網路工程師」

### ISSUE THREAD

**Issue by SimpsonAllen** [nodejs-tw/jobs#45]
自主研發 APP 產品、推廣發行自有品牌、、大數據決策強化等；諸多產品拿下 App Store 及 Google Play 冠軍頭排行(音樂、影視、娛樂、生活應用)。積極推動「數據驅動內容製作和廣告準投思維」，透過平台百萬使用者數據！ 2016 年投入平台全新的原創內容製作，獲得市場一致好評！

職務&條件：
- 負責產品後端架構設計。API 開發
- 應用最新雲端服務進行平台開發
- 熟悉 Node.js 及相關 framework 
- 熱愛行動 App，對於創業或 Startup 有熱情 
- 加分：具資訊安全及資料庫(MySQL & MongoDB)開發 / 具大量資料處理 & 效能優化經驗 / 熟悉AngularJS, ReactJS / 接觸過CI Server 例如 Jenkins等  

福利環境：活力愉快辦公環境；優渥福利制度

應徵方式：
履歷寄至 bruce@smartm.com.tw

**Comment by IvanWei** [comment]
[歐酷網路](https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=513f482d5b714e25496d3f2339333b6423d3f4770393b436c41473f222222221e1493f4f3634j49) 的職缺

**Comment by IvanWei** [comment]
感謝 @SimpsonAllen 的修正，也提出一個疑問。

資訊豐富度比 104 低，加上該公司最近 104 都更新，如果我是應徵者 104 會比較吸引我從那投履歷！
