### ISSUE TITLE
[ Larvata 徵才] 誠徵 NodeJS /javascript 工程師

### ISSUE THREAD

**Issue by crazylion** [nodejs-tw/jobs#49]
**公司介紹**

- 果子云熱愛創新、接受新觀念、新的工作模式。
- 我們的目標是成為最優秀的開發團隊，並與所有的成員都能找到自己的學習主題，一同成長。

website:  https://larvata.tw

**工作目標**

使用  nodejs 開發專案網站 

**工作內容**

- 使用  nodejs 開發專案網站 
- 編寫前端 javascript 程式

**工作要求**

- 熟悉 Node.js/Express 
- 熟悉軟體部署流程
- 熟悉 coffeeScript 尤佳
- 熟悉 jQuery , angularjs 
- 積極負責、具研究精神、對於新技術有高度興趣

**薪資福利**

NT$ 42,000 至 NT$ 60,000

**應徵方式**

履歷，以及與此工作內容相關的作品集
寄送至 info@larvata.tw，我們將盡快回覆

**Comment by appleboy** [comment]
看成 laravel
