### ISSUE TITLE
gogomaper - 誠徵後端工程師40K~60K

### ISSUE THREAD

**Issue by guodong1111** [nodejs-tw/jobs#5]
大家好，我們是gogomaper.Inc
正在尋找iOS developer & Backend(熟悉node.js)
過去我們成功打造出數款全球性App，也在歐洲、美國等23個國家達到不分類總榜的Top1，上過美國NBC新聞介紹。
如今我們回到台灣，地點環境變了，不變的是對於產品的熱情與堅持，相信好的產品，是由每個團隊成員共同參與討論激發出創新的火花，而非單純的執行命令者。
在這裡，你將能深入的參與產品中的每個環節，開發、規劃、以及產品營運，不管你是設計師、工程師、實習生，也都能看到透明公開的數據反饋，每個夥伴都能接觸到更寬廣的領域。
我們保證，在這裡，你將會打造出值得驕傲的產品，而不會害羞讓人知道這是你開發的...
公開透明是我們的承若，做好做滿更是我們對產品的堅持。
只要你對App有熱情，以及對於品質有所追求，都歡迎你與我們聯絡。
公司地址：位於忠孝東路四段，捷運國父紀念館站與忠孝敦化站中間。
iOS developer : 具備1年以上經驗，曾獨立完成產品從開發到上架。
待遇: 40K~60K
Backend : 熟悉node.js 有社交產品經驗佳
待遇: 40K~60K
email: segafun@gmail.com

**Comment by dca** [comment]
@guodong1111  嗨，這個職缺已經很久了，請問是否已經找到合適人選呢？如果找到了請記得告訴我們這個好消息，順便把 issue 關閉喔！ 👍
