### ISSUE TITLE
米蘭營銷策劃徵 NodeJS 工程師

### ISSUE THREAD

**Issue by milkmidi** [nodejs-tw/jobs#52]
職務名稱：NodeJS 工程師

迎接數位的時代。我們徵求對於 Web 有高度熱忱的夥伴一起創造新的互動感受。
在這裡，我們擁有一群強力的前端互動設計師，除了 HTML/Javascript 以外，也一直持續對其它的互動裝置/介面有高度的關注及瞭解。
在這裡，我們有一群天馬行空的創意團隊，常常會丟出充滿挑戰性的點子，讓工程師與創意能夠發揮出意想不到的成果。
在這裡，人都瘋瘋的，所以你也不用太正經。

工作內容：
1. 熟悉 Javascript、ES6、ES7
2. 熟悉 NodeJS , MongoDB 等 NoSQL Database
3. 熟悉 Express 或其他 Web 開發框架
4. 熟悉 Git 開發流程，Bug issue tracking
5. 撰寫單元測試
6. 後台管理介面開發
7. 伺服器效能最佳化
8. 樂於研究新型態的各種技術

其他加分條件：
1. 熟悉任一框架( angularjs2, reactjs , vuejs) Server Render
2. SEO
3. Restful API 實務經驗
4. FB API, Google Map API 整合經驗
5. 開發過其他程式語言(Java,Swift,C,C++,C#)
6. UI , UX 實務經驗

應徵時請準備 demo，有實際的作品會讓我們更快瞭解您的能力。

其他條件：	應徵前，請先了解我們是誰&我們在做啥： 
米蘭官網 http://medialand.tw/ 
米蘭粉絲團 https://www.facebook.com/medialandtw
104 連結
https://www.104.com.tw/job/?jobno=4yho2&jobsource=n104bank1

**Comment by PolarBearAndrew** [comment]
@dca  這個 104 的職缺已經關閉

**Comment by dca** [comment]
@PolarBearAndrew 感謝回報！

104 的職缺已經關閉，因此 close issue
