### ISSUE TITLE
Goodnight誠徵後端工程師

### ISSUE THREAD

**Issue by oney** [nodejs-tw/jobs#53]
要求同時熟悉Node.js與Ruby on Rails，有實際處理socket.io massive concurrency的經驗。
工作彈性，無須進公司，如果你能力夠好，可以挑戰一年進公司次數10次以內，只是就無緣見到辦公室裡的帥哥正妹。
寫程式速度快，Done is better than perfect

職位要求：
2年以上的Node.js、Ruby on Rails開發經驗
熟練Linux/Ubuntu、AWS EC2, S3, RDS
對後端開發流程、執行、測試以及上線的完整經驗
有SQL / NoSQL 數據庫 (PostgreSQL / Redis) 的經驗
有MVC及TDD/ BDD經驗以及理解
好的團隊合作能力以及溝通技巧

加分：
擁有DevOps能力，熟悉OpsWorks
熟悉其他NoSQL
有能力提出完整real time messaging and phone call架構

薪資福利：
月薪6-8萬起，保障14個月，能力強者最高年薪可到112萬
一年14天有薪年假，絕對放得到
生日有假放，請放心我們還是會幫你慶生的
每年定額員工訓練補助，專業表現好棒棒
旅遊補助，陽光大海度假去

地點：台北

聯絡方式：
請寄履歷到appdevoney@gmail.com

**Comment by kangshaojun** [comment]
你好 我用你的rn webrtc 跑起来了 真心不错  连接janus gateway
我的qq是 283796665   tel:18871002288
有一个linux  c c++   nodejs比较强的人可以给您推荐
