### ISSUE TITLE
Full Stack JS contractor, fluent English, $100k/mo

### ISSUE THREAD

**Issue by philharton** [nodejs-tw/jobs#55]
**Project**

We're building a LINE/FB chatbot platform for restaurants. The goals are for customers to give feedback, to come back to the restaurant more often, and to introduce their friends.

This project has 3 main components:

1. Web app for customers (React, Redux)
2. Native app for restaurant staff (React Native, Redux)
3. Services (AWS Lambda, Serverless, MongoDB)

**Team**

Hi, I'm Phil. I'm an ex-Google PM and I co-founded a startup in Beijing which was acquired by YY (Nasdaq: YY).

We will be working closely with our partner restaurant, Revel Eatery (https://www.facebook.com/reveleatery/) as a test case. If successful, we will build chatbots for other partner restaurants and eventually build a platform so any restaurant can create their own chatbot.

**Location**

忠孝敦化

**Requirements**

1. Learn fast
2. Communicate well
3. Think independently

Bonus points for experience with lean software development + git

**Work week**

4 days co-working, 1 day remote

**Compensation**

$100k/month
Daily healthy lunches provided by Freshies (https://www.facebook.com/freshiestw/)

**Contact**

If interested, please send me a code sample: phil@harton.org

Thanks for your time :)

**Comment by karocksjoelee** [comment]
is this still available ?

**Comment by philharton** [comment]
This position is no longer available
