### ISSUE TITLE
Loopd Inc. NodeJS 工程師[月薪至少11萬+]

### ISSUE THREAD

**Issue by loopdtw** [nodejs-tw/jobs#57]
**Working Location**
Taipei, Taiwan

**Requirements:**
Comfortable in the Agile/Scrum software development process
Thrives in a team atmosphere
Self-motivated & intellectually curious
Superb analytical skills
Strong written communication skills
Willingness to learn, adapt, and teach
Grounded in pragmatism
5+ years working with Node.js and Server Side JavaScript

**Responsibilities**
Integration of user-facing elements developed by front-end developers with server side logic
Writing reusable, testable, and efficient code
Design and implementation of low-latency, high-availability, and performant applications
Implementation of security and data protection
Integration of data storage solutions including MySQL, Redis, MongoDB etc.

**Perks**
Friday Happy Hours
1 day remote work
Gym membership reimbursement
Computer and equipment provided
Top of the class team and relaxed atmosphere

**Contact**
Please email allen.houng@etouches.com

**Comment by Easter1021** [comment]
寫的不夠清楚，起碼要說在哪兒工作
