### ISSUE TITLE
[台中徵才] Sr.全端  react/redux + nodejs  月薪60k up

### ISSUE THREAD

**Issue by unapapa** [nodejs-tw/jobs#58]
## 公司介紹

Tutor 以 LBS (location based service) 架構，將擁有專業技能的老師及需求端的學生資訊透明化，並提供全方面的線上家教配對平台服務。讓您想學什麼都不是問題。

試著想像，當您到了墾丁遊玩，看到衝浪高手正在享受衝浪時，除了稱羨還有觀望外，沒什麼可以做。但你可以透過 Tutor 上傳學習衝浪的需求，並即時獲得附近衝浪老師資訊。相信我，你會有意想不到的教練清單可以慢慢挑。

Tutor 的誕生理由很簡單：享受學習過程，並讓自己與眾不同。Tutor 以快速、有效的方式來滿足此雙邊市場模式，並在各個國家上線，讓您可以處在不同地方學習不同當地技能。任何地方都是學習的開始！

## 職缺說明

Full Stack Developer

- 前端：React、Redux、Bootstrap
- 後端：Node.js(Express)、Restful API
- 資料庫：MongoDB(Mongoose)
- 熟悉 Git 版本控制
- 加分：ES6(7)、Immutable、SASS、Koa、Redis、SEO
## 工作資訊

1. 地點：台中北區
2. 月薪：60k - 75k (依能力調整)
3. 時間：彈性
4. 高額獎金分配：每月2-3成利潤均分至現有成員
5. 不定期娛樂活動，電影、餐廳、旅遊
6. 高自由、舒適的上班環境

## 歡迎未來夥伴將cv寄至

mail: ezerch.tw@gmail.com

**Comment by SimonSun1988** [comment]
其實要前後都很熟悉的人，建議薪資範圍可以更大一點，比較好找到你要的人，要不然就是分兩個職缺。

**Comment by unapapa** [comment]
團隊除了每月固定薪資外，每月會將2-3成利潤均分，我相信對於一個穩定成長的團隊來說，單純獎金部分就有很高的機會高於月薪，並且隨著團隊成長而有明顯上升。當然還是很感謝您的指教～

**Comment by dca** [comment]
獎金蠻有誠意的啊，有 remote 缺嗎 XD

**Comment by unapapa** [comment]
嗨 Dca
由於團隊初創，很多細節仍需要及時討論，所以工程師部分無法remote～
謝囉

**Comment by Easter1021** [comment]
@unapapa  請問獎金是「包底抽成」嗎？ 

example: 假如某人薪水 5萬, 每月分得獎金 6萬

(包底抽成)  月薪 5萬 + 獎金 6 萬 = 11萬

(非包底抽成) 月薪 6萬

**Comment by unapapa** [comment]
@easter1021 當然是  **包底抽成！**
對團隊夥伴不會吝嗇

**Comment by decadehew** [comment]
請問應屆畢業生可否？

**Comment by SimonSun1988** [comment]
其實應該包底 + 抽成都要列出來相關資訊。

`單純獎金部分就有很高的機會高於月薪` 這句話，就代表著萬一公司今天營收不足，獎金也有可能會很少。

個人感覺拉。

**Comment by unapapa** [comment]
@decadehew 嗨嗨
再麻煩將cv寄到 ezerch.tw@gmail.com
另外附註可以進辦公室的時段(也就是排除上課時間)
期待您的cv囉～

**Comment by Easter1021** [comment]
非常認同 @unapapa 的阿沙力

**Comment by decadehew** [comment]
@unapapa 已發了
