### ISSUE TITLE
誠徵 Node.js 後端工程師 (無經驗~初中階可)

### ISSUE THREAD

**Issue by dca** [nodejs-tw/jobs#6]
## 工作內容
- 說實話
- 使用 Node.js 撰寫提供 Web、Mobile App 使用之後端程式
- 解決問題
- 寫測試
- 寫 API 文件
- Make 程式碼 better
- Make 工作流程 better
- Make 你自己 better

## 條件
- 熟悉 Node.js 開發環境
- 熟悉 JavaScript / ECMAScript 6
- 熟悉 MongoDB / MySQL / PostgreSQL 其中至少一項
- 能順利的使用 Git 進行團隊協作
- ***能做好做滿***

## 加分
- 寫過測試
- 熟悉其他更多東西（歡迎提出來讓我們知道）
- 能夠提供你的 Github 帳號
- 能夠提供你書櫃上的書單
- 能夠提供你平常關注的網站或部落格、或者是你自己有在寫是最好了

## 其他
- **自行參加黑客松享獎勵補休一日**
- 待遇：新台幣 30k-65k  * 14（依照上面各項的符合程度）
- 外派獎金
- 公司可提供工作用 Macbook Pro Retina、27 吋外接螢幕
- 工作地點：汐止大同路一段（近捷運南港展覽館、汐止交流道下）
- 上班時間：約 10:00~19:00 （含中午休息 1 小時）
- 不打卡、不加班（請讓老闆回家 ~~陪老婆~~ 帶小孩）、對自己負責
- 周休二日
- 愉悅、活潑、自由的工作環境
- 提供舒適的人體工學椅
- 履歷請寄到 【hr "AT" brocas.com.tw】，標題【應徵 Android Engineer - 姓名】

## 公司簡介

我們相信顧客的軟體必須要是最好的。
我們是軟體開發的設計顧問，提供顧客完整的解決方案以及更完美的產品

在我們公司，你可以—
- 勇敢挑戰未知的可能性
- 學習各式各樣新穎的技術
- 處在歡樂滿點的工作環境

而且一定會有一個東西很吸引你，那就是—

### **滿足你內心最底層那充滿創造力的渴望**

歡迎來到軟體時代，用程式碼創造你的世界，完成自己用心打造的作品
彈指之間創造歷史，享受從無到有的過程，擁有自己創作的成就感
提供最有效的解決方案，實作堅若磐石的技術，結合有趣的網路行銷，超越客戶的期待，協助客戶的業務成長。
創造員工、公司與客戶三體共榮的結果，是我們致力追求的目標！

#### 另有 Frontend 職缺
https://github.com/f2etw/jobs/issues/73

#### 同場加映 - Android 工程師
https://gist.github.com/brocas-dev/e6589fdeba26d7c8a323

**Comment by SimonSun1988** [comment]
公司氣氛和樂，同事相處融洽，制度嚴謹卻有人性，好公司不來嗎?!

**Comment by Rukeith** [comment]
真動心～

**Comment by roackb2** [comment]
想請問公司名稱跟網址？
接不接受專案合作？
這是我的 npm 帳號:
https://www.npmjs.com/~roackb2
還有LinkedIn:
https://tw.linkedin.com/in/roackb2

**Comment by dca** [comment]
您好，我們公司名稱是 Brocas 布洛卡斯，如果有其他想法、合作也歡迎來信洽談喔 :+1:

**Comment by dca** [comment]
更新我們的特別補休規定

**Comment by dca** [comment]
暫時關閉，近期內我們有緣再相見
