### ISSUE TITLE
【行動商務】API工程師 - 易遊網 ezTravel

### ISSUE THREAD

**Issue by tonywang0122** [nodejs-tw/jobs#61]
# 公司名稱
易遊網股份有限公司 www.eztravel.com.tw

# 工作內容
1. 負責API設計、開發與維護 
2. 撰寫API文件 

# 職務要求
1. 熟悉 Javascript(ES6)，Node JS及相關framework例如Express等 
2. 熟悉RESTful API設計 
3. 具備系統分析及規劃能力，有後端架構設計、API開發經驗佳 
4. 使用過版本控制工具，有用過Git者佳 
5. 具備NoSQL(Ex:Redis/MangoDB/Cassandra等)相關開發經驗為加分項目 
6. 具備React Native開發經驗為加分項目 

工作配Macbook 及 Dell 大螢幕喔~

# 薪資
38,000 ~ 80,000 / 13個月

# 聯絡方式
Tony Wang
E-mail: tonywang@eztravel.com.tw
Facebook: https://www.facebook.com/whsienc

**Comment by HamiltonWang** [comment]
不再需要了嗎？
