### ISSUE TITLE
【徵】前端工程師 Fandora 映雲科技有限公司

### ISSUE THREAD

**Issue by Fandorashop** [nodejs-tw/jobs#62]
**<在這裡你可以獲得的>** 

1. 首年即享年假 12 天，我們相信 Life Work Balance 你會做得更好 
2. 自動冒出零食的點心櫃，開心爆笑的工作氣氛，總是會發生各種好玩的事 
3. 辦公室離捷運松山站只要 3 分鐘，松山火車站 1 分鐘，還有饒河夜市好方便 
4. 各種學習分享，讓你學到專業以外的更多事情 

**<你需要做的是>** 

1. 協助維護並開發 EC 網站新功能 
2. 新技術研究 
3. 寫前端代碼 

**<我們希望你擁有>** 

1. React / HTML / CSS 
2. LESS or SASS 
3. 可以接受對於 coding style 的要求 
4. 對於 code quality 有追求 
5. 能夠進行獨立作業和執行, 確保自己手上的專案項目能準確有效率的完成 
6. 具有高抗壓性及彈性，以數據為依歸去調整執行方向，且能快速反應 
7. 開放心態且積極學習新知和新技術，能主動提出新的方法和自己的觀點 
8. 能與團隊合作一同達成目標 

**<有這些更加分>** 

1. Redux 
2. 三年以上前端開發經驗 
3. AMP 
4. BYOC 
5. 介面設計經驗 

如果你喜歡我們做的事情，認同我們的理念，並符合上述所說條件， 
趕快將履歷投遞過來吧!!! 
我們非常歡迎你加入我們的行列!!! 

Fandora Shop https://fandorashop.com/tw/ 
毛孩市集 https://petpetgo.com/

工作待遇：月薪 4萬元 至 8萬元
工作性質：全職
上班地點：台北市南港區八德路4段768巷5號2樓
 
可以寄信到 hr@fandora.co 
或是 直接在104 投遞喔~
https://www.104.com.tw/job/?jobno=5cp5k&jobsource=

**Comment by dca** [comment]
偷問一下 BYOC 是什麼

**Comment by clonn** [comment]
LAN party指的是由一群人暫時性、通常也是自發性的帶著他們的電腦，在一個地方將電腦以局域網鏈接的聚會，這樣的聚會大部份是以玩多人網絡遊戲為目的。 這樣的局域網可大可小，從只有兩三個人到數千人都有。小型聚會可以自發性的舉辦。大型的聚會則需要有組織事前規劃與準備。 LAN party一詞有時會與網吧或遊戲場混淆。雖然所提供的服務很類似，但是LAN party通常是參加者要自備電腦，而非主辦者事先準備好電腦。

**Comment by gwokae** [comment]
@dca bring you own computer

**Comment by Easter1021** [comment]
是否考慮部份外包？ 我可以試試

**Comment by dca** [comment]
ref #63
