### ISSUE TITLE
【徵】Node.js 後端工程師 Fandora 映雲科技

### ISSUE THREAD

**Issue by Fandorashop** [nodejs-tw/jobs#63]
**<在這裡你可以獲得的>** 

1. 首年即享年假 12 天，我們相信 Life Work Balance 你會做得更好 
2. 自動冒出零食的點心櫃，開心爆笑的工作氣氛，總是會發生各種好玩的事 
3. 辦公室離捷運松山站只要 3 分鐘，松山火車站 1 分鐘，還有饒河夜市好方便 
4. 各種學習分享，讓你學到專業以外的更多事情 

**<你需要做的是>** 

1. API 後端開發與維護 
2. 維護 MariaDB / MySQL資料庫系統 
3. 伺服器維運 AWS EC2 + Ubuntu + Docker 
4. 用 SQL 寫一些資料查詢來協助行銷與業務 

**<我們希望你擁有>** 

1. Node.js 一定要有 50,000 行以上經驗 
2. Express.js / Sequelize / AWS EC2 / SQL / Docker / Ubuntu 
3. 能夠進行獨立作業和執行, 確保自己手上的專案項目能準確有效率的完成 
4. 具有高抗壓性及彈性，以數據為依歸去調整執行方向，且能快速反應 
5. 開放心態且積極學習新知和新技術，能主動提出新的方法和自己的觀點 
6. 能與團隊合作一同達成目標 

**<有這些更加分>** 

1. Google TensorFlow 
2. Amazon RedShift 
3. Amazon Machine Learning 

如果你喜歡我們做的事情，認同我們的理念，並符合上述所說條件， 
趕快將履歷投遞過來吧!!! 
我們非常歡迎你加入我們的行列!!! 

Fandora Shop https://fandorashop.com/tw/ 
毛孩市集 https://petpetgo.com/

工作待遇：月薪 4萬元 至 8萬元
工作性質：全職
上班地點：台北市南港區八德路4段768巷5號2樓
上班時段：日班
休假制度：週休二日
接受身份：上班族、應屆畢業生
工作經歷：1年以上

嗨嗨 大家可以直接投履歷到 hr@fandora.co
或是 直接上104投遞喔~
https://www.104.com.tw/job/?jobno=5cp4v&jobsource=

**Comment by Fandorashop** [comment]
推推

**Comment by dca** [comment]
這樣推太偷懶了喔 🤔

**Comment by Fandorashop** [comment]
XD 被發現了 原諒我 拜託 ><
