### ISSUE TITLE
【徵】Full Stack Web Developer (70k - 150k per month)

### ISSUE THREAD

**Issue by hawaiishinji** [nodejs-tw/jobs#76]
R&W is a creative agency with headquarters in Hong Kong and studios in Taipei and NYC. We help startups and global brands design, build, and grow mobile apps, video games, VR apps, IoT hardware, and the cloud services that light them up. Our clients include some of the largest and fastest growing global tech and consumer brands based in the US, Europe, and Asia.

The team at R&W has built more than 100 apps, games, cloud services, marketplaces, publisher platforms, and developer platforms. Our special sauce is design focused on growth, and several of the apps & services we’ve built have grown to 10M+ users. We're growing rapidly and building a team of web developers in Taipei. We’re looking for some talented full stack engineers who want to get bigger, deeper experience on global products.

## Some general requirements: 
- Have built full stack web products before. 
- Desire to grow the active user base for the products you create.
- Comfortable taking projects from the design phase to a stable production release. 
- Care about how the products that you build satisfy the users who try your products
- Ok to discuss design, architecture, specs, and details in **English**.  
- Like to choose the best tools and tech for the job.

## Tech you should know: 
- Front-end: HTML, CSS, Javascript, js frameworks like Angular or React (we’re deep on Angular)
- Back-end: Any of Node, PHP, Rails. (we’re deep on Node)
- Server: SasS solutions like Firebase and Parse, AWS, and generally Linux servers 
- Tools/Misc.: git, unit testing, automated deploys
- Analytics: Segment, Mixpanel, Facebook Pixels, and marketing automation tools.

## Location
台北市中正區

## Salary
NT $ 70k - 150k per month

## Contact
If you feel that this is a good match for your skillsets - please send your linkedin link or resume to anggie@roamandwander.com or reach out to Anggie at 02-2321 9592 for more info.

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
