### ISSUE TITLE
node.js developer (Odessa or remote - salary up to 5500$/month)

### ISSUE THREAD

**Issue by maria-belonozhko** [nodejs-tw/jobs#77]
Come join a small team of the best developers we can find around the world to build our next big product, MoovCheckout Instant. We are enjoying working hard together as a team and looking to add a few more key people to the effort. Moovweb currently powers experiences visited by one-third of mobile Americans each month.
https://jobs.dou.ua/companies/softesis/vacancies/45635/

CONTACTS
Skype — barrracuda
telegram @OpticsPlanet
viber 097 543 63 33
www.facebook.com/maria.belonozhko

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
