### ISSUE TITLE
星友科技 - nodejs 資深工程師 80~120k (13個月)

### ISSUE THREAD

**Issue by LightChang** [nodejs-tw/jobs#8]
# 星友科技 nodejs 資深工程師 80~120k (13個月)

### 公司名稱
星友科技

### 工作地點
台北市建國北路一段 96 號 8 樓之1

### 工作時間
一天8小時，08:00~12:00 13:30~17:30，午休時間：12:00~13:30。
彈性上班時間：08:00~09:00，因遲到不足時數於當日下班前補回。

### 職缺名稱
nodejs 資深工程師

### 薪資範圍
80~120k (13個月)

### 任職後一年內主要工作方向
1. 全新 nodejs 軟體團隊
2. 由新竹硬體團隊提供 dll 串接指紋設備
3. 往上接瀏覽器 extensions 或 Win/Mac/Linux Application Client 做指紋辨識相關應用
4. 再往上接 Server Side 做 AP 服務與其他系統串接
5. 再往上提供指紋辨識第三方認證機制（有點像 OAuth）

### 工作內容
1. 依需求確認書規劃 npm 功能
2.  npm 自我測試、回報結果工具撰寫
3. 程式發佈、自動更新流程
4. 協助 nodejs 工程師完成任務
4.1. 依需求規劃撰寫單元測試
4.2. 各項產品功能 npm 開發
4.3. 依設備提供 dll 撰寫對應 extension
4.4. 實作 OAuth, FIDO, Third 驗證流程

### 預計使用技能
1. 應用程式開發：nw.js
2. 網頁管理介面開發：express, swig
3. 同步處理工具：async
4. 動態呼叫 C/C++ libraries：addons
5. 瀏覽器擴充功能撰寫：Firefox, Chrome extension
6. 資料加解密：crypto
7. 軟體測試流程：mocha, should, istanbul, karma, winston
8. 程式發佈、派版：npk

## 聯絡人
- 聯絡人：張饒輝
- email: light@mail.startek-eng.com
- phone: 0988-911679 or 02-2501-3585

# 制式資料

### 公司名稱
星友科技股份有限公司

### 聯絡地址
台北市建國北路一段 96 號 8 樓之1
新竹市東區園區二路54號3樓(新竹科學園區)

### 行業別：
電腦／週邊設備製造

### 行業說明：
指紋辨識系統研發製造

### 網站位址：
http://www.startek.com.tw/

### 公司簡介

星友公司成立於1989年，為國內唯一自行研發指紋辨識技術的廠商。擁有多項指紋辨識專利與軟體著作權。自創建以來，陸續榮獲經濟部國家產品精品獎、銀質獎、金質獎，與德國IF世界優良工業產品設計獎等獎項，業界成就深受肯定。

星友公司的指紋辨識系列產品，乃是結合光電、自動控制、數位、類比信號處理及微電腦處理等尖端科技，開發適用各種領域的指紋辨識產品。應用範圍諸如門禁管制、差勤管理、身份認證、資訊安全、流程控管，以及雲端運用等。

目前，在台灣已有約40萬人，超過一百多家政府機關與公司行號，使用星友公司的指紋辨識系統控管門禁。全世界第一台指紋認證自動櫃員機乃星友與IBM於1996年完成，當時為南非STANDARD BANK的專案。2002年本公司更進一步與日本富士通合作，共同開發新一代的指紋機，2003年初已裝機近千台於日本某政府單位。表現出星友科技日益精湛的產品技術，獲得國內外人士的肯定。

當前國際紛擾事件頻傳，網路交易日益頻繁，安全認證已為各國注目焦點，而指紋辨識又為生物辨識認證應用上之關鍵技術。星友擁有指紋辨識的核心技術，除既有的產品開發外，也可與各專業領域合作開發新產品或授權。本公司秉著CIT的精神，在指紋辨識領域不斷求新求變，相信將於安全認證潮流下另創台灣企業新史，享譽國際。
產品簡介

## 營業項目
電子零組件製造業 
資訊軟體服務業 

一、研究、開發、生產、製造、銷售下列產品： 
1. 指紋監控系統 
2. 指紋、文字及影像輸出入設備 
3. 網路認證及資訊安全處理設備 
4. 上述產品之軟體及技術諮詢服務 

二、前各項有關產品之進出口貿易業務

### 公司制度
勞保、健保、員工在職教育訓練、週休二日

### 獎金福利
員工生日禮金、年終獎金、三節獎金

### 保險福利
員工體檢、勞退提撥金

### 餐飲福利
伙食津貼

### 補助福利
員工結婚補助、生育補助、員工國內、外進修補助、員工及眷屬喪葬補助

### 其他福利
舒適安全及人性化的工作環境與組織氣氛 　
福委會之生育、傷病、住院、急難、婚喪禮金等多項補助、員工年度旅遊、員工聯誼會、年終尾牙等活動補助 　
提供科學園區優質宿舍申請（含單身及眷舍）
總公司周邊免費停車位（含汽車及機車位）

**Comment by touhonoob** [comment]
請問工時？

**Comment by LightChang** [comment]
@touhonoob  抱歉，已補充。目前個人經驗，沒有超過 18:30 下班。

**Comment by ddman** [comment]
有需要外包找我吧，我最喜歡玩新東西了XD

**Comment by job-blacklist** [comment]
推工作感覺不錯，但該曾與該徵求者共事過，僅推工作可以嘗試不推該徵求者。

**Comment by LightChang** [comment]
@job-blacklist 雖然不知道樓上是誰，但如果以前跟你共事造成您的不快，還請見諒。

**Comment by ddman** [comment]
@job-blacklist 雖然不知道您是誰，但如果以前共事造成您的不快，還請見諒。

**Comment by dca** [comment]
@LightChang  嗨，這個職缺已經很久了，請問是否已經找到合適人選呢？如果找到了請記得告訴我們這個好消息，順便把 issue 關閉喔！ 👍

**Comment by LightChang** [comment]
@dca 請把這個職缺關閉吧，謝謝您。
