### ISSUE TITLE
[徵才] [8 Interactive] Backend/Fullstack Engineer 1M ~ 1.5M yr

### ISSUE THREAD

**Issue by jeffjen** [nodejs-tw/jobs#81]
# Backend / Fullstack Engineer

- 公司名稱: 8 Interactive Limited
- 公司地址: 台北市內湖區洲子街80號7樓
- 公司網址: https://no8.io
- 公司信箱: im8@no8.io (請投遞透過以下徵才網站投履歷)
- 薪資: 1M～1.5M／yr
- 徵才網址: https://www.yourator.co/companies/8Interactive/jobs/2296
- 工作時間: 責任制，正常情況下 40hr / week

## 什麼是 8？

8 是將對話轉變為商機，給中小企業及創業店家的通訊行銷工具。

透過 8 行銷平台，您可以串連 Facebook 和 LINE@ 等通訊軟體，
讓您的廣告和創意構想更為生動地傳達給顧客

## 為什麼要用 8？

早在去年 2016 年，Uber 和 Facebook Messenger 整合使其透過通訊
平台有更廣更方便的運用。

Uber 的開發者體驗主管 Chris Messina 當時也說到：

2016 Will be the year of conversational commerce.

這句話背後所闡述的不只是一個事實，更是多家大型公司及現今的趨勢。
然而，大多數人提到對話式商務時講的是「機器人」、「銷售」等關鍵字，
但對我們而言，對話式商務的意義遠遠不止如此。

品牌、企業或個人透過聊天訊息、對話等與另一方互動，完成某件商業行為，
就是對話式商務的範疇。
對話式商務涵蓋了行銷、廣告、品牌形象建立、客戶服務…各式各樣的服務，
以對話的形式完成。它可以是個購物平台：透過聊天訊息販賣一件商品、
提供客戶訂餐，也可以是個行銷平台：將新品宣傳單發送出去、直效的廣告，
更可以是個客服平台：解答問題、退換貨的管道… 一切都可以在聊天室中以
訊息的模式完成

## 工作內容

徵求一起開發並改良 Number8 系統的同志！
- 協助開發以 Docker + Node.JS 為核心的 Micro-Service 框架
- 利用現在實用化的 Function As A Service (FaaS) 達成快速部署和功能

We are looking for a backend engineer to help build and improve our current system: 
- Help build and improve our Docker + Node.JS based Micro-Service Architecture
- Leverage Function as a Service (FaaS) design to provide rapid deployment and feature.

我們期待的戰友能：
- 積極且強烈的執念推進這個產品直至完備
- 彈性的應對外部和內部的變化

Qualified Candidates brings the following traits
- Strong desire and initiative in driving the product to its completion. 
- Adapt to changing infrastructure and platform

你需要的技能：
- Node.JS
  - Strong understanding in Asynchrounous programming

我們推薦的技能：
- Mongo and Redis
  - Use of mongo shell to debug and/or export data
  - Use of Redis as Cache and PubSub
  - Monitor Replica-Set

- Docker
  - Understand basics in container usage and inter-container communication
  - Provision compose file

- AWS
  - Strong understanding in common services
    - IAM, EC2, Lambda, ALB, S3, CloudFront, CloudWatch Logs
  - Able to daftly manage credentials and configuration

- Angular2 / React.JS
  - Proficient in either MVC framework

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
