### ISSUE TITLE
【Eatgether】 Backend Engineer 後端網站工程師

### ISSUE THREAD

**Issue by magicsky0831** [nodejs-tw/jobs#83]
我們相信，一頓飯可以連結全世界。

《食我餐飲顧問股份有限公司》是一個成立自2014年的新創公司，致力於透過網路科技創新應用服務，「創造更美好的用餐體驗」。分別於2014年與2016年完成種子與天使輪投資，分別來自於聯合報系與多位業界知名天使投資人。公司主要的產品為自2016年上線就獲得廣大好評的聚餐交友APP《Eatgether》。

目前團隊成員約十人，是個平均年齡近30歲，同時具備年輕活力與技能經驗的團隊。動靜分明是我們的團隊文化，彈性自律是我們的工作風格，在這裡沒有太多的規範，上下班不打卡，也可自行安排工作時間，高度的自律搭配目標導向的管理模式，成就了一個快而精實的新創團隊。目前整個團隊都聚焦在開發Eatgether，朝著打造一個來自台灣的國際化餐飲社交平台而努力。我們認為新創公司的人才就是一切，每個加入的人都會改變這個團隊與產品，非常期待有你的加入！

公司地址：台北市中正區忠孝西路一段50號22f-9 (台北車站正對面，捷運出口10秒到)
公司官網：https://eatgether.com/

【工作任務】
・規劃與開發Eatgether App與網站的後端資料庫與API架構

【能力需求】
・熟悉Web後端開發技術, 如 JavaScript, PHP, SQL
・熟悉 PHP + Laravel or NodeJS + Koa2
・具備實際的網站前後端開發經驗與作品
・熟悉 Git 協作
・熟悉AWS伺服器系統
・具IT網路管理與維運或系統軟體開發經驗
・有數據分析系統或後台開發之相關經驗
・配合App開發維護後台API
・有高度責任感,溝通能力強,注重團隊合作
・GIT版本開發

【加分條件】
・提供 GitHub 或曾參與過平台類型作品參考

薪資範圍

年薪60-100萬 (依年資)

工時/特休

週休二日，表定10:00-19:00，午休一小時，彈性上下班不打卡
比照勞基法，國定假日見紅就放

福利/推薦項

合夥與配股機會
公假外部進修課程與購書補助

聯絡方式

履歷請寄：jobs@eatme.tw

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
