### ISSUE TITLE
[Hiring] 新加坡Fintech找Node.js Backend Engineer, 1.2M-2.2M

### ISSUE THREAD

**Issue by dorothychen13** [nodejs-tw/jobs#84]
This is Dorothy from Recruit Express.
Specialized in Information Technology and Software Development recruitment services.
My client - A SG Fintech Company is looking to expand their APAC 2nd RD Center in Taiwan. They are looking for Backend Engineers, if you are inspired to take up new challenges, this is the best choice for you!

Job Title: Backend Engineer
Location: Taipei City, near MRT Taipei Main Station
On-board Date: ASAP
Salary: NT$1.2M-2.2M

Responsibilities:
Design, develop, implement, and maintain new and existing web-based applications
Coordinate with engineering to define and prioritize engineering projects.
Able to work in a dynamic and diverse engineering culture - every day, we learn from each other, brainstorm and execute ideas, and play ping pong to unwind...
Build a great product that impacts consumer online behavior - we’re proud that our product is changing the way people shop online
Interest in exploring and learning the latest technologies in the industry.

Requirements:
5+ years of relevant work experience
Hands on experience working with NodeJS
Experience working with cloud services like AWS, Heroku or Google cloud platform
Experience on different databases. Relational (PostgreSQL, MySQL, ...) or NoSQL(MongoDB, CouchDB, Cassandra)
Worked with scalable systems of at least 80 production servers
Extensive REST API development experience
Excellent verbal and written communication skills, a team player with strong analytical, problem solving, debugging, and troubleshooting skills

Contact:
Please feel free to send me your CV and GitHub via dorothy@recruitexpress.com.tw
Thanks.

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
