### ISSUE TITLE
{誠徵} NodeJS後端工程師

### ISSUE THREAD

**Issue by Jojohr** [nodejs-tw/jobs#86]
Responsibilities

1. Backend Restful API design and development

2. Database design and implementation

Requirements

1. Strong experience in Node.js, Experienced in ES6 and Promise

2. Familiarity with Expressjs or Koa framework, Experienced in REST API design

3. Familiarity with SQL and relational database, such as MySQL

4. Familiarity with Git and Markdown

5. Good teamwork and communication skills

工作内容

1. 後端Restful API的設計與開發

2. 資料庫模型設計與維護

具備條件

1. 熟悉NodeJS, ES6, Promise

2. 熟悉Express或Koa等框架, 有Restful API設計經驗

3. 熟悉SQL語法和MySQL等關係型資料庫的操作與使用

4. 熟悉Git, Markdown

5. 良好的團隊合作和溝通能力

詳細內容請參考104:https://www.104.com.tw/job/?jobno=5jb42&jobsource=

歡迎有志者至104投遞履歷，謝謝!

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
