### ISSUE TITLE
[誠徵] Software Architect (JavaScript & Node.js Preferred)

### ISSUE THREAD

**Issue by ryanhanwu** [nodejs-tw/jobs#87]
## 團隊簡介/地點
地點：紐約
EdLab: 我們是一個位於哥大的研究開發單位，專精於研究與探索未來的教育產業，以下僅列出部份重點，詳情請點最底下連結。

## 工作內容
   - 2/3 研究與開發，1/3 規劃與架構
   - 參與整個敏捷開發流程
   - 教育與領導資淺團員成長
   - Dev Team 人數: 5~7 ，Research 以及 UIX 另計

## 能力需求
- 對教育有熱忱
- 有獨力解決問題能力
- 有以下相關知識與經驗
  - SPA 開發
  - API 設計、規劃與實作
  - SEO (Google)
  - 資料庫設計與拓展
  - 程式碼重構
  - 軟體部署開發管理

## 加分
- 熟我們現在的 [Stack](http://go.tc.edu/stack) 或者你可以把它變更好
- 熟 Node.js, React.js, Python, MySQL, Docker, and AWS
- 有 AI, ML 或 Recommendation System 經驗

## 薪資範圍
- 面議，過去經驗是十萬鎂+/年 
- 紐約目前禁止公司在招聘過程中詢問應徵者過去的薪酬紀錄，有能力者歡迎來挑戰

## 工時/特休
- 美國時間很多，7 hrs/day
- 休假也還可以，15 days/year

## 福利/推薦項
- 在美國該有的保險都有 (Health, Dental, Vision...etc)
- 你在哥大上課免費 （你知道這樣值多少錢吧)

## 聯絡方式

其他詳細內容以及履歷投遞請[點這裡](http://go.tc.edu/architect)
有問題歡迎私下詢問我 ryan.wu at tc.edu

**Comment by dca** [comment]
職缺超過一年，先關閉，若有需要再另外發，謝謝。
