### ISSUE TITLE
新創APP團隊徵兼職夥伴(React Native、Mongo DB、NodeJS任一

### ISSUE THREAD

**Issue by h94g41up** [nodejs-tw/jobs#89]
●徵才條件：對React Native、Mongo DB、Node.js任一者有興趣、開發經驗一年以上者

●薪資條件：無薪資，相對的報酬為開發多少就佔團隊股份多少(詳聊過後，若相信團隊產品有機會成功，投報率不小)

●工作環境：遠距開發、在家辦公、線上開會、工作時數自己安排、做多少就占多少團隊股權

●團隊狀況：
1.團隊內兩位Senior開發者，會幫忙 Code Review 幫助一起進步、學習
2.團隊內產品開發經驗充足，拿過台灣appstore排行榜第一、也有產品累積全台400萬用戶的紀錄
3.團隊運作以敏捷開發為核心，有4位來自以敏捷開發為招牌的軟體公司(名字不便公開、可私聊)
4.團隊是台北加速器APPWORKS #13育成團隊之一，創業經驗累積兩年，成功機率較高
5.團隊的題目成功機率高，語言交換題目是源自於CEO曾在全球最大語言交換APP公司工作經驗而來

●新創題目：
語言交換，是指透過與外語人士大量的口語對話，讓外語溝通變的流利、甚至深入交談。但媒合語伴的困難、外語人士時間安排的不確定性都導致了學習效率的低下。
這也是個長期被外語教育忽略的市場，我們想以即時媒合全球的語言交換客群線上對話，將平時閒置的語言技能資源以共享經濟的方式進行創新，透過平台分享自己中文能力換取自己與外國人練習的機會，讓每個人都能隨時隨地高效的進行語言交換。
我們相信透過這樣的方式能服務全球每年將近五千萬渴望與母語人士練習的人們，未來若成功將嘗試前進海外，既可以學習開發、創業、產品，運氣好創業成功了也能賺上一筆。

●產品概念細節不少，希望有熱忱想要改變世界語言學習的人能聯繫，可寄信至 h94g41up@gmail.com 或FB加好友 https://www.facebook.com/h94g41up

**Comment by tsoliangwu0130** [comment]
哈囉你好，

我的名字是吳祚亮，目前在美國擔任軟體工程師，工作經驗包含實習經驗大概兩年多快三年，主要專職開發 API 及 DevOps。日前在 GitHub 上看到您的徵才貼文有高度興趣，但對於目前貴司的產品及工作模式仍然不太了解，不知道是否方便可以與您約個時間聊聊呢？

附上我的 GitHub 及個人網站：
GitHub: https://github.com/tsoliangwu0130 <https://github.com/tsoliangwu0130>
Website: https://tsoliangwu.com/

期待您的回信，
祚亮
