### ISSUE TITLE
Loopd - NodeJS 資深工程師 (薪水＋股份)

### ISSUE THREAD

**Issue by ayhoung** [nodejs-tw/jobs#9]
NodeJS 資深工程師 (薪水＋股份)

**公司名稱**
Loopd Inc.
(https://loopd.com)

**工作地點**
台灣大學育成中心

**工作內容**
依需求確認書規劃 npm 功能
npm 自我測試、回報結果工具撰寫
程式發佈、自動更新流程
協助 nodejs 工程師完成任務 4.1. 依需求規劃撰寫單元測試 4.2. 各項產品功能 npm 開發 4.3. 依設備提供 dll 撰寫對應 extension 4.4. 實作 OAuth, FIDO, Third 驗證流程
預計使用技能

**加分**
- Golang 經驗
- 前端經驗
- Mobile app 開發經驗
- Devops 經驗

聯絡人：Allen Houng
email: allen@loopd.com
phone: 0984-228-001

**Comment by dca** [comment]
超過一年故先關閉。如果還有招募需求，請更新並重發喔，謝謝！
