### ISSUE TITLE
全端

### ISSUE THREAD

**Issue by billiebbb** [nodejs-tw/jobs#92]
# 徵求一名全職全端

## 工作需求：

1. 曾以 vue.js 或 react.js 或 angular.js 實作過 project
1. 熟 mysql, mongodb
1. 熟 git flow
1. 有 API 實作經驗
1. 年資不限
1. 略知 devOps

## 工作休假：
時間 am 9:00 ~ pm 5:30(彈性調整)
依資歷及能力可視狀況遠端工作
週休二日
例假依人事行政局行事曆

## 工作地點：

1. 高雄市
2. 台北市
3. 遠端任何地點

## 薪資福利：

月薪 40K ~ 80K (年薪13個月) 
依勞基法給與特休

## 應徵方式
請直接 email 至 billiebbb@gmail.com  或私訊 https://www.messenger.com/t/BillieGoodGirl

**Comment by dca** [comment]
好低調的職缺，沒有工作內容也沒有公司名稱嗎？

**Comment by billiebbb** [comment]
@dca 
https://www.104.com.tw/job/?jobno=5xs7e&jobsource=n104bank1
